//! sqlx `SqlitePool`, PRAGMA setup (design §15.2), `sqlx::migrate!` embedding,
//! and the repo CRUD layer (thin wrappers over **compile-time-checked** sqlx
//! `query!`/`query_as!` macros).
//!
//! ## Compile-time SQL validation
//!
//! Every query in this module uses `sqlx::query!` / `sqlx::query_as!`, which
//! validate the SQL text, column names, column types, and bind-parameter types
//! against the committed `.sqlx/` offline cache at **compile time**. This
//! catches schema drift before the code can even build.
//!
//! The `.sqlx/` cache is generated by `cargo sqlx prepare` against a fully
//! migrated reference database (see the project README / CI). CI sets
//! `SQLX_OFFLINE=true` so no live `DATABASE_URL` is needed during builds.
//!
//! Repo functions map the SQLite `INTEGER` columns onto `i64` in the row
//! structs (sqlx decodes `INTEGER` → `i64`) and cast to the idiomatic `i32` /
//! `bool` used by [`hydra_core::model`] at the boundary.

use std::str::FromStr;
use std::time::Duration;

use sqlx::migrate::MigrateError;
use sqlx::sqlite::{SqliteConnectOptions, SqliteJournalMode, SqlitePoolOptions, SqliteSynchronous};
use sqlx::SqlitePool;

use hydra_core::model::{
    LimitRole, Provider, ProviderKey, ProviderKeyBinding, ProviderModel, Tenant, TenantModel,
    TenantProvider,
};

use crate::crypto::{self, CryptoError, KeyProvider, Sealed};

// ---------------------------------------------------------------------------
// Pool initialisation + PRAGMAs (design §15.2)
// ---------------------------------------------------------------------------

/// Connect a `SqlitePool` and apply the production PRAGMAs (design §15.2):
/// `journal_mode=WAL`, `synchronous=NORMAL`, `busy_timeout=5000`,
/// `foreign_keys=ON`, `mmap_size=134217728`.
///
/// PRAGMAs are applied **per connection** via [`SqliteConnectOptions`]:
/// `foreign_keys` is connection-scoped in SQLite, so a one-shot
/// `PRAGMA foreign_keys=ON` on a single connection would not propagate to the
/// rest of the pool — the connect-options builder applies it to every fresh
/// connection, which is the root-cause-correct approach for a multi-connection
/// file-backed production pool.
///
/// For `:memory:` URLs the pool is pinned to a single connection: each
/// in-memory connection is otherwise an isolated empty database, so a pool
/// with more than one connection would make migrations invisible to other
/// connections (the canonical sqlx in-memory test pattern).
pub async fn init_pool(url: &str) -> Result<SqlitePool, sqlx::Error> {
    let opts = SqliteConnectOptions::from_str(url)?
        .journal_mode(SqliteJournalMode::Wal)
        .synchronous(SqliteSynchronous::Normal)
        .busy_timeout(Duration::from_millis(5000))
        .foreign_keys(true)
        .pragma("mmap_size", "134217728");

    let is_memory = url.contains(":memory:");
    let pool = SqlitePoolOptions::new()
        .max_connections(if is_memory { 1 } else { 8 })
        .connect_with(opts)
        .await?;
    Ok(pool)
}

/// Run the embedded migrations (`sqlx::migrate!("./migrations")`).
pub async fn run_migrate(pool: &SqlitePool) -> Result<(), MigrateError> {
    sqlx::migrate!("./migrations").run(pool).await
}

// ---------------------------------------------------------------------------
// Row structs (mirror SQLite types) + conversions to core entities.
// ---------------------------------------------------------------------------

#[derive(sqlx::FromRow, Debug, Clone)]
struct ProviderRow {
    id: String,
    key: String,
    name: String,
    endpoint: String,
    weight: i64,
    created_at: String,
    updated_at: String,
    /// Per-provider concurrency admission policy (design-admission-queue §5).
    /// Nullable: NULL ⇒ use ProxyConfig defaults (opt-in). SQLite INTEGER → i64.
    max_concurrency: Option<i64>,
    max_queue_depth: Option<i64>,
    queue_wait_timeout_ms: Option<i64>,
}

/// Cast a nullable SQLite INTEGER (decoded as `Option<i64>`) to `Option<u32>`,
/// rejecting negative values (defensive — a manual DB edit should not panic the
/// loader). Negative ⇒ `None` (treated as "use defaults").
fn to_u32_opt(v: Option<i64>) -> Option<u32> {
    v.filter(|n| *n >= 0).map(|n| n as u32)
}

/// Same as [`to_u32_opt`] but for `u64` (`queue_wait_timeout_ms`).
fn to_u64_opt(v: Option<i64>) -> Option<u64> {
    v.filter(|n| *n >= 0).map(|n| n as u64)
}

impl From<ProviderRow> for Provider {
    fn from(r: ProviderRow) -> Self {
        Provider {
            id: r.id,
            key: r.key,
            name: r.name,
            endpoint: r.endpoint,
            weight: r.weight as i32,
            created_at: r.created_at,
            updated_at: r.updated_at,
            max_concurrency: to_u32_opt(r.max_concurrency),
            max_queue_depth: to_u32_opt(r.max_queue_depth),
            queue_wait_timeout_ms: to_u64_opt(r.queue_wait_timeout_ms),
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct ProviderModelRow {
    id: String,
    key: String,
    name: String,
    provider_id: String,
    status: i64,
}

impl From<ProviderModelRow> for ProviderModel {
    fn from(r: ProviderModelRow) -> Self {
        ProviderModel {
            id: r.id,
            key: r.key,
            name: r.name,
            provider_id: r.provider_id,
            status: r.status as i32,
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct ProviderKeyRow {
    id: String,
    provider_id: String,
    // Nullable in the schema (ALTER TABLE ADD COLUMN BLOB has no NOT NULL), but
    // always populated by `insert_provider_key`. The `query_as!` macro enforces
    // nullability at compile time, so these are Option and unwrapped in to_model.
    api_key_ciphertext: Option<Vec<u8>>,
    api_key_nonce: Option<Vec<u8>>,
    key_version: i64,
    created_at: String,
}

impl ProviderKeyRow {
    /// Decrypt the ciphertext into a plaintext `ProviderKey` model. Plaintext
    /// exists only transiently here, then lives in-memory in the model (never
    /// persisted). Requires a [`KeyProvider`] because decryption is I/O on the
    /// master key.
    fn to_model(&self, kp: &dyn KeyProvider) -> Result<ProviderKey, CryptoError> {
        let ciphertext = self
            .api_key_ciphertext
            .as_ref()
            .ok_or(CryptoError::Decrypt)?;
        let nonce_bytes = self.api_key_nonce.as_ref().ok_or(CryptoError::Decrypt)?;
        let nonce: [u8; crypto::NONCE_LEN] = nonce_bytes
            .as_slice()
            .try_into()
            .map_err(|_| CryptoError::Decrypt)?;
        let sealed = Sealed {
            ciphertext: ciphertext.clone(),
            nonce,
            key_version: self.key_version as u32,
        };
        let plaintext = kp.open(&sealed)?;
        let api_key = String::from_utf8(plaintext).map_err(|_| CryptoError::NotUtf8)?;
        Ok(ProviderKey {
            id: self.id.clone(),
            provider_id: self.provider_id.clone(),
            api_key,
            created_at: self.created_at.clone(),
        })
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct TenantRow {
    id: String,
    name: String,
    domain: String,
    auth_url: String,
    cert_key: Option<String>,
    cert_file: Option<String>,
    enabled: i64,
    created_at: String,
    updated_at: String,
}

impl From<TenantRow> for Tenant {
    fn from(r: TenantRow) -> Self {
        Tenant {
            id: r.id,
            name: r.name,
            domain: r.domain,
            auth_url: r.auth_url,
            cert_key: r.cert_key,
            cert_file: r.cert_file,
            enabled: r.enabled != 0,
            created_at: r.created_at,
            updated_at: r.updated_at,
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct TenantProviderRow {
    id: String,
    tenant_id: String,
    provider_id: String,
}

impl From<TenantProviderRow> for TenantProvider {
    fn from(r: TenantProviderRow) -> Self {
        TenantProvider {
            id: r.id,
            tenant_id: r.tenant_id,
            provider_id: r.provider_id,
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct TenantModelRow {
    id: String,
    tenant_id: String,
    model_key: String,
}

impl From<TenantModelRow> for TenantModel {
    fn from(r: TenantModelRow) -> Self {
        TenantModel {
            id: r.id,
            tenant_id: r.tenant_id,
            model_key: r.model_key,
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct LimitRoleRow {
    id: String,
    name: String,
    matching_key: Option<String>,
    matching_model: Option<String>,
    matching_tenant: Option<String>,
    matching_provider: Option<String>,
    limit_count: Option<i64>,
    limit_token: Option<i64>,
    window: String,
    enabled: i64,
    created_at: String,
}

impl From<LimitRoleRow> for LimitRole {
    fn from(r: LimitRoleRow) -> Self {
        LimitRole {
            id: r.id,
            name: r.name,
            matching_key: r.matching_key,
            matching_model: r.matching_model,
            matching_tenant: r.matching_tenant,
            matching_provider: r.matching_provider,
            limit_count: r.limit_count,
            limit_token: r.limit_token,
            window: r.window,
            enabled: r.enabled != 0,
            created_at: r.created_at,
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct ProviderKeyBindingRow {
    id: String,
    key_prefix: String,
    provider_id: String,
    enabled: i64,
    created_at: String,
    updated_at: String,
}

impl From<ProviderKeyBindingRow> for ProviderKeyBinding {
    fn from(r: ProviderKeyBindingRow) -> Self {
        ProviderKeyBinding {
            id: r.id,
            key_prefix: r.key_prefix,
            provider_id: r.provider_id,
            enabled: r.enabled != 0,
            created_at: r.created_at,
            updated_at: r.updated_at,
        }
    }
}

// ---------------------------------------------------------------------------
// CRUD — Provider
// ---------------------------------------------------------------------------

/// Insert a provider. Violating the UNIQUE `key` constraint returns
/// [`sqlx::Error::Database`] (UNIQUE violation).
pub async fn insert_provider(pool: &SqlitePool, p: &Provider) -> Result<(), sqlx::Error> {
    // Bind Option conversions to locals so the temporaries live long enough
    // for the sqlx macro's borrow checker.
    let max_concurrency = p.max_concurrency.map(|v| v as i64);
    let max_queue_depth = p.max_queue_depth.map(|v| v as i64);
    let queue_wait_timeout_ms = p.queue_wait_timeout_ms.map(|v| v as i64);
    sqlx::query!(
        "INSERT INTO provider (id, key, name, endpoint, weight, created_at, updated_at, \
         max_concurrency, max_queue_depth, queue_wait_timeout_ms) \
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        p.id,
        p.key,
        p.name,
        p.endpoint,
        p.weight,
        p.created_at,
        p.updated_at,
        max_concurrency,
        max_queue_depth,
        queue_wait_timeout_ms,
    )
    .execute(pool)
    .await?;
    Ok(())
}

/// Fetch a single provider by id; `Err(RowNotFound)` when absent.
pub async fn get_provider(pool: &SqlitePool, id: &str) -> Result<Provider, sqlx::Error> {
    let row = sqlx::query_as!(
        ProviderRow,
        r#"SELECT id as "id!", key, name, endpoint, weight, created_at, updated_at,
                  max_concurrency, max_queue_depth, queue_wait_timeout_ms
           FROM provider WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

/// All providers, ordered by `created_at`.
pub async fn list_providers(pool: &SqlitePool) -> Result<Vec<Provider>, sqlx::Error> {
    let rows = sqlx::query_as!(
        ProviderRow,
        r#"SELECT id as "id!", key, name, endpoint, weight, created_at, updated_at,
                  max_concurrency, max_queue_depth, queue_wait_timeout_ms
           FROM provider ORDER BY created_at"#
    )
    .fetch_all(pool)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

/// Update a provider's mutable fields.
pub async fn update_provider(pool: &SqlitePool, p: &Provider) -> Result<(), sqlx::Error> {
    let max_concurrency = p.max_concurrency.map(|v| v as i64);
    let max_queue_depth = p.max_queue_depth.map(|v| v as i64);
    let queue_wait_timeout_ms = p.queue_wait_timeout_ms.map(|v| v as i64);
    sqlx::query!(
        "UPDATE provider SET key = ?, name = ?, endpoint = ?, weight = ?, updated_at = ?, \
         max_concurrency = ?, max_queue_depth = ?, queue_wait_timeout_ms = ? \
         WHERE id = ?",
        p.key,
        p.name,
        p.endpoint,
        p.weight,
        p.updated_at,
        max_concurrency,
        max_queue_depth,
        queue_wait_timeout_ms,
        p.id,
    )
    .execute(pool)
    .await?;
    Ok(())
}

/// Delete a provider (CASCADE removes its models/keys and tenant_provider links).
pub async fn delete_provider(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM provider WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — ProviderModel
// ---------------------------------------------------------------------------

/// Insert a provider model. The CHECK (`status IN (1,0,-1)`) and
/// UNIQUE(`key`,`provider_id`) constraints are enforced by SQLite.
pub async fn insert_provider_model(
    pool: &SqlitePool,
    m: &ProviderModel,
) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "INSERT INTO provider_model (id, key, name, provider_id, status) VALUES (?, ?, ?, ?, ?)",
        m.id,
        m.key,
        m.name,
        m.provider_id,
        m.status,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_provider_model(pool: &SqlitePool, id: &str) -> Result<ProviderModel, sqlx::Error> {
    let row = sqlx::query_as!(
        ProviderModelRow,
        r#"SELECT id as "id!", key, name, provider_id, status
           FROM provider_model WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_provider_models(pool: &SqlitePool) -> Result<Vec<ProviderModel>, sqlx::Error> {
    let rows = sqlx::query_as!(
        ProviderModelRow,
        r#"SELECT id as "id!", key, name, provider_id, status
           FROM provider_model ORDER BY key, provider_id"#
    )
    .fetch_all(pool)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

/// Update a provider model's mutable fields (`key`, `name`, `status`).
pub async fn update_provider_model(
    pool: &SqlitePool,
    m: &ProviderModel,
) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "UPDATE provider_model SET key = ?, name = ?, status = ? WHERE id = ?",
        m.key,
        m.name,
        m.status,
        m.id,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn delete_provider_model(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM provider_model WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — ProviderKey
// ---------------------------------------------------------------------------

/// Map a [`CryptoError`] into a sqlx error so the repo functions keep a single
/// `Result<_, sqlx::Error>` return type. `CryptoError` is `Send + Sync + Error`.
fn crypto_to_sqlx(e: CryptoError) -> sqlx::Error {
    sqlx::Error::Decode(Box::new(e))
}

pub async fn insert_provider_key(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    k: &ProviderKey,
) -> Result<(), sqlx::Error> {
    let sealed = kp.seal(k.api_key.as_bytes()).map_err(crypto_to_sqlx)?;
    let nonce: &[u8] = &sealed.nonce;
    sqlx::query!(
        "INSERT INTO provider_key (id, provider_id, api_key_ciphertext, api_key_nonce, \
         key_version, created_at) VALUES (?, ?, ?, ?, ?, ?)",
        k.id,
        k.provider_id,
        sealed.ciphertext,
        nonce,
        sealed.key_version,
        k.created_at,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_provider_key(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    id: &str,
) -> Result<ProviderKey, sqlx::Error> {
    let row = sqlx::query_as!(
        ProviderKeyRow,
        r#"SELECT id as "id!", provider_id, created_at, api_key_ciphertext, api_key_nonce,
                  key_version
           FROM provider_key WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    row.to_model(kp).map_err(crypto_to_sqlx)
}

/// All provider keys (the loader groups them by `provider_id`).
pub async fn list_provider_keys(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
) -> Result<Vec<ProviderKey>, sqlx::Error> {
    let rows = sqlx::query_as!(
        ProviderKeyRow,
        r#"SELECT id as "id!", provider_id, created_at, api_key_ciphertext, api_key_nonce,
                  key_version
           FROM provider_key ORDER BY provider_id, created_at"#
    )
    .fetch_all(pool)
    .await?;
    rows.iter()
        .map(|r| r.to_model(kp).map_err(crypto_to_sqlx))
        .collect()
}

/// Keys belonging to a single provider (ordered by creation).
pub async fn list_provider_keys_by_provider(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    provider_id: &str,
) -> Result<Vec<ProviderKey>, sqlx::Error> {
    let rows = sqlx::query_as!(
        ProviderKeyRow,
        r#"SELECT id as "id!", provider_id, created_at, api_key_ciphertext, api_key_nonce,
                  key_version
           FROM provider_key WHERE provider_id = ? ORDER BY created_at"#,
        provider_id,
    )
    .fetch_all(pool)
    .await?;
    rows.iter()
        .map(|r| r.to_model(kp).map_err(crypto_to_sqlx))
        .collect()
}

pub async fn delete_provider_key(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM provider_key WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — Tenant
// ---------------------------------------------------------------------------

/// Insert a tenant. `auth_url` is NOT NULL → inserting with an empty/non-null
/// value is fine; a NULL would error at the SQLite layer.
pub async fn insert_tenant(pool: &SqlitePool, t: &Tenant) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "INSERT INTO tenant (id, name, domain, auth_url, cert_key, cert_file, enabled, \
         created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
        t.id,
        t.name,
        t.domain,
        t.auth_url,
        t.cert_key,
        t.cert_file,
        t.enabled,
        t.created_at,
        t.updated_at,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_tenant(pool: &SqlitePool, id: &str) -> Result<Tenant, sqlx::Error> {
    let row = sqlx::query_as!(
        TenantRow,
        r#"SELECT id as "id!", name, domain, auth_url, cert_key, cert_file, enabled,
                  created_at, updated_at
           FROM tenant WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_tenants(pool: &SqlitePool) -> Result<Vec<Tenant>, sqlx::Error> {
    let rows = sqlx::query_as!(
        TenantRow,
        r#"SELECT id as "id!", name, domain, auth_url, cert_key, cert_file, enabled,
                  created_at, updated_at
           FROM tenant ORDER BY created_at"#
    )
    .fetch_all(pool)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

/// Update a tenant's mutable fields (`name`, `domain`, `auth_url`, cert paths,
/// `enabled`, `updated_at`).
pub async fn update_tenant(pool: &SqlitePool, t: &Tenant) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "UPDATE tenant SET name = ?, domain = ?, auth_url = ?, cert_key = ?, cert_file = ?, \
         enabled = ?, updated_at = ? WHERE id = ?",
        t.name,
        t.domain,
        t.auth_url,
        t.cert_key,
        t.cert_file,
        t.enabled,
        t.updated_at,
        t.id,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn delete_tenant(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM tenant WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — TenantProvider
// ---------------------------------------------------------------------------

pub async fn insert_tenant_provider(
    pool: &SqlitePool,
    tp: &TenantProvider,
) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "INSERT INTO tenant_provider (id, tenant_id, provider_id) VALUES (?, ?, ?)",
        tp.id,
        tp.tenant_id,
        tp.provider_id,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_tenant_provider(
    pool: &SqlitePool,
    id: &str,
) -> Result<TenantProvider, sqlx::Error> {
    let row = sqlx::query_as!(
        TenantProviderRow,
        r#"SELECT id as "id!", tenant_id, provider_id
           FROM tenant_provider WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_tenant_providers(pool: &SqlitePool) -> Result<Vec<TenantProvider>, sqlx::Error> {
    let rows = sqlx::query_as!(
        TenantProviderRow,
        r#"SELECT id as "id!", tenant_id, provider_id
           FROM tenant_provider ORDER BY tenant_id, provider_id"#
    )
    .fetch_all(pool)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

pub async fn delete_tenant_provider(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM tenant_provider WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — TenantModel
// ---------------------------------------------------------------------------

pub async fn insert_tenant_model(pool: &SqlitePool, tm: &TenantModel) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "INSERT INTO tenant_model (id, tenant_id, model_key) VALUES (?, ?, ?)",
        tm.id,
        tm.tenant_id,
        tm.model_key,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_tenant_model(pool: &SqlitePool, id: &str) -> Result<TenantModel, sqlx::Error> {
    let row = sqlx::query_as!(
        TenantModelRow,
        r#"SELECT id as "id!", tenant_id, model_key
           FROM tenant_model WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_tenant_models(pool: &SqlitePool) -> Result<Vec<TenantModel>, sqlx::Error> {
    let rows = sqlx::query_as!(
        TenantModelRow,
        r#"SELECT id as "id!", tenant_id, model_key
           FROM tenant_model ORDER BY tenant_id, model_key"#
    )
    .fetch_all(pool)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

pub async fn delete_tenant_model(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM tenant_model WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — LimitRole
// ---------------------------------------------------------------------------

pub async fn insert_limit_role(pool: &SqlitePool, r: &LimitRole) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "INSERT INTO limit_role (id, name, matching_key, matching_model, matching_tenant, \
         matching_provider, limit_count, limit_token, window, enabled, created_at) \
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        r.id,
        r.name,
        r.matching_key,
        r.matching_model,
        r.matching_tenant,
        r.matching_provider,
        r.limit_count,
        r.limit_token,
        r.window,
        r.enabled,
        r.created_at,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_limit_role(pool: &SqlitePool, id: &str) -> Result<LimitRole, sqlx::Error> {
    let row = sqlx::query_as!(
        LimitRoleRow,
        r#"SELECT id as "id!", name, matching_key, matching_model, matching_tenant,
                  matching_provider, limit_count, limit_token, window, enabled, created_at
           FROM limit_role WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_limit_roles(pool: &SqlitePool) -> Result<Vec<LimitRole>, sqlx::Error> {
    let rows = sqlx::query_as!(
        LimitRoleRow,
        r#"SELECT id as "id!", name, matching_key, matching_model, matching_tenant,
                  matching_provider, limit_count, limit_token, window, enabled, created_at
           FROM limit_role ORDER BY created_at"#
    )
    .fetch_all(pool)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

/// Update a limit role's mutable fields.
pub async fn update_limit_role(pool: &SqlitePool, r: &LimitRole) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "UPDATE limit_role SET name = ?, matching_key = ?, matching_model = ?, \
         matching_tenant = ?, matching_provider = ?, limit_count = ?, limit_token = ?, \
         window = ?, enabled = ? WHERE id = ?",
        r.name,
        r.matching_key,
        r.matching_model,
        r.matching_tenant,
        r.matching_provider,
        r.limit_count,
        r.limit_token,
        r.window,
        r.enabled,
        r.id,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn delete_limit_role(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM limit_role WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — provider_key_binding (design §7.1b)
// ---------------------------------------------------------------------------

/// Insert a binding. Violating the UNIQUE `key_prefix` constraint returns a
/// sqlx UNIQUE violation (→ 409 by the admin layer).
pub async fn insert_provider_key_binding(
    pool: &SqlitePool,
    b: &ProviderKeyBinding,
) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "INSERT INTO provider_key_binding (id, key_prefix, provider_id, enabled, created_at, \
         updated_at) VALUES (?, ?, ?, ?, ?, ?)",
        b.id,
        b.key_prefix,
        b.provider_id,
        b.enabled,
        b.created_at,
        b.updated_at
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_provider_key_binding(
    pool: &SqlitePool,
    id: &str,
) -> Result<ProviderKeyBinding, sqlx::Error> {
    let row = sqlx::query_as!(
        ProviderKeyBindingRow,
        r#"SELECT id as "id!", key_prefix, provider_id, enabled, created_at, updated_at
           FROM provider_key_binding WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_provider_key_bindings(
    pool: &SqlitePool,
) -> Result<Vec<ProviderKeyBinding>, sqlx::Error> {
    let rows = sqlx::query_as!(
        ProviderKeyBindingRow,
        r#"SELECT id as "id!", key_prefix, provider_id, enabled, created_at, updated_at
           FROM provider_key_binding ORDER BY key_prefix"#
    )
    .fetch_all(pool)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

/// Update a binding's mutable fields (prefix / provider / enabled).
pub async fn update_provider_key_binding(
    pool: &SqlitePool,
    b: &ProviderKeyBinding,
) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "UPDATE provider_key_binding SET key_prefix = ?, provider_id = ?, enabled = ?, \
         updated_at = ? WHERE id = ?",
        b.key_prefix,
        b.provider_id,
        b.enabled,
        b.updated_at,
        b.id
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn delete_provider_key_binding(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM provider_key_binding WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}
