//! sqlx `SqlitePool`, PRAGMA setup (design §15.2), `sqlx::migrate!` embedding,
//! and the repo CRUD layer (thin wrappers over **compile-time-checked** sqlx
//! `query!`/`query_as!` macros).
//!
//! ## Compile-time SQL validation
//!
//! Every query in this module uses `sqlx::query!` / `sqlx::query_as!`, which
//! validate the SQL text, column names, column types, and bind-parameter types
//! against the committed `.sqlx/` offline cache at **compile time**. This
//! catches schema drift before the code can even build.
//!
//! The `.sqlx/` cache is generated by `cargo sqlx prepare` against a fully
//! migrated reference database (see the project README / CI). CI sets
//! `SQLX_OFFLINE=true` so no live `DATABASE_URL` is needed during builds.
//!
//! Repo functions map the SQLite `INTEGER` columns onto `i64` in the row
//! structs (sqlx decodes `INTEGER` → `i64`) and cast to the idiomatic `i32` /
//! `bool` used by [`hydra_core::model`] at the boundary.

use std::str::FromStr;
use std::time::Duration;

use sqlx::migrate::MigrateError;
use sqlx::sqlite::{SqliteConnectOptions, SqliteJournalMode, SqlitePoolOptions, SqliteSynchronous};
use sqlx::SqlitePool;

use hydra_core::model::{
    LimitRole, Provider, ProviderKey, ProviderKeyBinding, ProviderModel, Tenant, TenantModel,
    TenantProvider,
};

use crate::crypto::{self, CryptoError, KeyProvider, Sealed};

// ---------------------------------------------------------------------------
// Pool initialisation + PRAGMAs (design §15.2)
// ---------------------------------------------------------------------------

/// Connect a `SqlitePool` and apply the production PRAGMAs (design §15.2):
/// `journal_mode=WAL`, `synchronous=NORMAL`, `busy_timeout=5000`,
/// `foreign_keys=ON`, `mmap_size=134217728`.
///
/// PRAGMAs are applied **per connection** via [`SqliteConnectOptions`]:
/// `foreign_keys` is connection-scoped in SQLite, so a one-shot
/// `PRAGMA foreign_keys=ON` on a single connection would not propagate to the
/// rest of the pool — the connect-options builder applies it to every fresh
/// connection, which is the root-cause-correct approach for a multi-connection
/// file-backed production pool.
///
/// For `:memory:` URLs the pool is pinned to a single connection: each
/// in-memory connection is otherwise an isolated empty database, so a pool
/// with more than one connection would make migrations invisible to other
/// connections (the canonical sqlx in-memory test pattern).
pub async fn init_pool(url: &str) -> Result<SqlitePool, sqlx::Error> {
    let opts = SqliteConnectOptions::from_str(url)?
        .journal_mode(SqliteJournalMode::Wal)
        .synchronous(SqliteSynchronous::Normal)
        .busy_timeout(Duration::from_millis(5000))
        .foreign_keys(true)
        .pragma("mmap_size", "134217728");

    let is_memory = url.contains(":memory:");
    let pool = SqlitePoolOptions::new()
        .max_connections(if is_memory { 1 } else { 8 })
        .connect_with(opts)
        .await?;
    Ok(pool)
}

/// Run the embedded migrations (`sqlx::migrate!("./migrations")`).
pub async fn run_migrate(pool: &SqlitePool) -> Result<(), MigrateError> {
    sqlx::migrate!("./migrations").run(pool).await
}

// ---------------------------------------------------------------------------
// Row structs (mirror SQLite types) + conversions to core entities.
// ---------------------------------------------------------------------------

#[derive(sqlx::FromRow, Debug, Clone)]
struct ProviderRow {
    id: String,
    key: String,
    name: String,
    endpoint: String,
    weight: i64,
    created_at: String,
    updated_at: String,
    /// Per-provider concurrency admission policy (design-admission-queue §5).
    /// Nullable: NULL ⇒ use ProxyConfig defaults (opt-in). SQLite INTEGER → i64.
    max_concurrency: Option<i64>,
    max_queue_depth: Option<i64>,
    queue_wait_timeout_ms: Option<i64>,
}

/// Cast a nullable SQLite INTEGER (decoded as `Option<i64>`) to `Option<u32>`,
/// rejecting negative values (defensive — a manual DB edit should not panic the
/// loader). Negative ⇒ `None` (treated as "use defaults").
fn to_u32_opt(v: Option<i64>) -> Option<u32> {
    v.filter(|n| *n >= 0).map(|n| n as u32)
}

/// Same as [`to_u32_opt`] but for `u64` (`queue_wait_timeout_ms`).
fn to_u64_opt(v: Option<i64>) -> Option<u64> {
    v.filter(|n| *n >= 0).map(|n| n as u64)
}

impl From<ProviderRow> for Provider {
    fn from(r: ProviderRow) -> Self {
        Provider {
            id: r.id,
            key: r.key,
            name: r.name,
            endpoint: r.endpoint,
            weight: r.weight as i32,
            created_at: r.created_at,
            updated_at: r.updated_at,
            max_concurrency: to_u32_opt(r.max_concurrency),
            max_queue_depth: to_u32_opt(r.max_queue_depth),
            queue_wait_timeout_ms: to_u64_opt(r.queue_wait_timeout_ms),
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct ProviderModelRow {
    id: String,
    key: String,
    name: String,
    provider_id: String,
    status: i64,
}

impl From<ProviderModelRow> for ProviderModel {
    fn from(r: ProviderModelRow) -> Self {
        ProviderModel {
            id: r.id,
            key: r.key,
            name: r.name,
            provider_id: r.provider_id,
            status: r.status as i32,
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct ProviderKeyRow {
    id: String,
    provider_id: String,
    // Nullable in the schema (ALTER TABLE ADD COLUMN BLOB has no NOT NULL), but
    // always populated by `insert_provider_key`. The `query_as!` macro enforces
    // nullability at compile time, so these are Option and unwrapped in to_model.
    api_key_ciphertext: Option<Vec<u8>>,
    api_key_nonce: Option<Vec<u8>>,
    key_version: i64,
    created_at: String,
}

impl ProviderKeyRow {
    /// Decrypt the ciphertext into a plaintext `ProviderKey` model. Plaintext
    /// exists only transiently here, then lives in-memory in the model (never
    /// persisted). Requires a [`KeyProvider`] because decryption is I/O on the
    /// master key.
    fn to_model(&self, kp: &dyn KeyProvider) -> Result<ProviderKey, CryptoError> {
        let ciphertext = self
            .api_key_ciphertext
            .as_ref()
            .ok_or(CryptoError::Decrypt)?;
        let nonce_bytes = self.api_key_nonce.as_ref().ok_or(CryptoError::Decrypt)?;
        let nonce: [u8; crypto::NONCE_LEN] = nonce_bytes
            .as_slice()
            .try_into()
            .map_err(|_| CryptoError::Decrypt)?;
        let sealed = Sealed {
            ciphertext: ciphertext.clone(),
            nonce,
            key_version: self.key_version as u32,
        };
        let plaintext = kp.open(&sealed)?;
        let api_key = String::from_utf8(plaintext).map_err(|_| CryptoError::NotUtf8)?;
        Ok(ProviderKey {
            id: self.id.clone(),
            provider_id: self.provider_id.clone(),
            api_key,
            created_at: self.created_at.clone(),
        })
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct TenantRow {
    id: String,
    name: String,
    domain: String,
    auth_url: String,
    cert_key: Option<String>,
    cert_file: Option<String>,
    enabled: i64,
    created_at: String,
    updated_at: String,
}

impl From<TenantRow> for Tenant {
    fn from(r: TenantRow) -> Self {
        Tenant {
            id: r.id,
            name: r.name,
            domain: r.domain,
            auth_url: r.auth_url,
            cert_key: r.cert_key,
            cert_file: r.cert_file,
            enabled: r.enabled != 0,
            created_at: r.created_at,
            updated_at: r.updated_at,
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct TenantProviderRow {
    id: String,
    tenant_id: String,
    provider_id: String,
}

impl From<TenantProviderRow> for TenantProvider {
    fn from(r: TenantProviderRow) -> Self {
        TenantProvider {
            id: r.id,
            tenant_id: r.tenant_id,
            provider_id: r.provider_id,
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct TenantModelRow {
    id: String,
    tenant_id: String,
    model_key: String,
}

impl From<TenantModelRow> for TenantModel {
    fn from(r: TenantModelRow) -> Self {
        TenantModel {
            id: r.id,
            tenant_id: r.tenant_id,
            model_key: r.model_key,
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct LimitRoleRow {
    id: String,
    name: String,
    matching_key: Option<String>,
    matching_model: Option<String>,
    matching_tenant: Option<String>,
    matching_provider: Option<String>,
    limit_count: Option<i64>,
    limit_token: Option<i64>,
    window: String,
    enabled: i64,
    created_at: String,
}

impl From<LimitRoleRow> for LimitRole {
    fn from(r: LimitRoleRow) -> Self {
        LimitRole {
            id: r.id,
            name: r.name,
            matching_key: r.matching_key,
            matching_model: r.matching_model,
            matching_tenant: r.matching_tenant,
            matching_provider: r.matching_provider,
            limit_count: r.limit_count,
            limit_token: r.limit_token,
            window: r.window,
            enabled: r.enabled != 0,
            created_at: r.created_at,
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct ProviderKeyBindingRow {
    id: String,
    key_prefix: String,
    provider_id: String,
    enabled: i64,
    created_at: String,
    updated_at: String,
}

impl From<ProviderKeyBindingRow> for ProviderKeyBinding {
    fn from(r: ProviderKeyBindingRow) -> Self {
        ProviderKeyBinding {
            id: r.id,
            key_prefix: r.key_prefix,
            provider_id: r.provider_id,
            enabled: r.enabled != 0,
            created_at: r.created_at,
            updated_at: r.updated_at,
        }
    }
}

// ---------------------------------------------------------------------------
// CRUD — Provider
// ---------------------------------------------------------------------------

/// Insert a provider. Violating the UNIQUE `key` constraint returns
/// [`sqlx::Error::Database`] (UNIQUE violation).
pub async fn insert_provider(pool: &SqlitePool, p: &Provider) -> Result<(), sqlx::Error> {
    // Bind Option conversions to locals so the temporaries live long enough
    // for the sqlx macro's borrow checker.
    let max_concurrency = p.max_concurrency.map(|v| v as i64);
    let max_queue_depth = p.max_queue_depth.map(|v| v as i64);
    let queue_wait_timeout_ms = p.queue_wait_timeout_ms.map(|v| v as i64);
    sqlx::query!(
        "INSERT INTO provider (id, key, name, endpoint, weight, created_at, updated_at, \
         max_concurrency, max_queue_depth, queue_wait_timeout_ms) \
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        p.id,
        p.key,
        p.name,
        p.endpoint,
        p.weight,
        p.created_at,
        p.updated_at,
        max_concurrency,
        max_queue_depth,
        queue_wait_timeout_ms,
    )
    .execute(pool)
    .await?;
    Ok(())
}

/// Fetch a single provider by id; `Err(RowNotFound)` when absent.
pub async fn get_provider(pool: &SqlitePool, id: &str) -> Result<Provider, sqlx::Error> {
    let row = sqlx::query_as!(
        ProviderRow,
        r#"SELECT id as "id!", key, name, endpoint, weight, created_at, updated_at,
                  max_concurrency, max_queue_depth, queue_wait_timeout_ms
           FROM provider WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

/// All providers, ordered by `created_at`.
pub async fn list_providers(pool: &SqlitePool) -> Result<Vec<Provider>, sqlx::Error> {
    let rows = sqlx::query_as!(
        ProviderRow,
        r#"SELECT id as "id!", key, name, endpoint, weight, created_at, updated_at,
                  max_concurrency, max_queue_depth, queue_wait_timeout_ms
           FROM provider ORDER BY created_at"#
    )
    .fetch_all(pool)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

/// Update a provider's mutable fields.
pub async fn update_provider(pool: &SqlitePool, p: &Provider) -> Result<(), sqlx::Error> {
    let max_concurrency = p.max_concurrency.map(|v| v as i64);
    let max_queue_depth = p.max_queue_depth.map(|v| v as i64);
    let queue_wait_timeout_ms = p.queue_wait_timeout_ms.map(|v| v as i64);
    sqlx::query!(
        "UPDATE provider SET key = ?, name = ?, endpoint = ?, weight = ?, updated_at = ?, \
         max_concurrency = ?, max_queue_depth = ?, queue_wait_timeout_ms = ? \
         WHERE id = ?",
        p.key,
        p.name,
        p.endpoint,
        p.weight,
        p.updated_at,
        max_concurrency,
        max_queue_depth,
        queue_wait_timeout_ms,
        p.id,
    )
    .execute(pool)
    .await?;
    Ok(())
}

/// Delete a provider (CASCADE removes its models/keys and tenant_provider links).
pub async fn delete_provider(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM provider WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — ProviderModel
// ---------------------------------------------------------------------------

/// Insert a provider model. The CHECK (`status IN (1,0,-1)`) and
/// UNIQUE(`key`,`provider_id`) constraints are enforced by SQLite.
pub async fn insert_provider_model(
    pool: &SqlitePool,
    m: &ProviderModel,
) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "INSERT INTO provider_model (id, key, name, provider_id, status) VALUES (?, ?, ?, ?, ?)",
        m.id,
        m.key,
        m.name,
        m.provider_id,
        m.status,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_provider_model(pool: &SqlitePool, id: &str) -> Result<ProviderModel, sqlx::Error> {
    let row = sqlx::query_as!(
        ProviderModelRow,
        r#"SELECT id as "id!", key, name, provider_id, status
           FROM provider_model WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_provider_models(pool: &SqlitePool) -> Result<Vec<ProviderModel>, sqlx::Error> {
    let rows = sqlx::query_as!(
        ProviderModelRow,
        r#"SELECT id as "id!", key, name, provider_id, status
           FROM provider_model ORDER BY key, provider_id"#
    )
    .fetch_all(pool)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

/// Update a provider model's mutable fields (`key`, `name`, `status`).
pub async fn update_provider_model(
    pool: &SqlitePool,
    m: &ProviderModel,
) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "UPDATE provider_model SET key = ?, name = ?, status = ? WHERE id = ?",
        m.key,
        m.name,
        m.status,
        m.id,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn delete_provider_model(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM provider_model WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — ProviderKey
// ---------------------------------------------------------------------------

/// Map a [`CryptoError`] into a sqlx error so the repo functions keep a single
/// `Result<_, sqlx::Error>` return type. `CryptoError` is `Send + Sync + Error`.
fn crypto_to_sqlx(e: CryptoError) -> sqlx::Error {
    sqlx::Error::Decode(Box::new(e))
}

pub async fn insert_provider_key(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    k: &ProviderKey,
) -> Result<(), sqlx::Error> {
    let sealed = kp.seal(k.api_key.as_bytes()).map_err(crypto_to_sqlx)?;
    let nonce: &[u8] = &sealed.nonce;
    sqlx::query!(
        "INSERT INTO provider_key (id, provider_id, api_key_ciphertext, api_key_nonce, \
         key_version, created_at) VALUES (?, ?, ?, ?, ?, ?)",
        k.id,
        k.provider_id,
        sealed.ciphertext,
        nonce,
        sealed.key_version,
        k.created_at,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_provider_key(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    id: &str,
) -> Result<ProviderKey, sqlx::Error> {
    let row = sqlx::query_as!(
        ProviderKeyRow,
        r#"SELECT id as "id!", provider_id, created_at, api_key_ciphertext, api_key_nonce,
                  key_version
           FROM provider_key WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    row.to_model(kp).map_err(crypto_to_sqlx)
}

/// All provider keys (the loader groups them by `provider_id`).
pub async fn list_provider_keys(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
) -> Result<Vec<ProviderKey>, sqlx::Error> {
    let rows = sqlx::query_as!(
        ProviderKeyRow,
        r#"SELECT id as "id!", provider_id, created_at, api_key_ciphertext, api_key_nonce,
                  key_version
           FROM provider_key ORDER BY provider_id, created_at"#
    )
    .fetch_all(pool)
    .await?;
    rows.iter()
        .map(|r| r.to_model(kp).map_err(crypto_to_sqlx))
        .collect()
}

/// Keys belonging to a single provider (ordered by creation).
pub async fn list_provider_keys_by_provider(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    provider_id: &str,
) -> Result<Vec<ProviderKey>, sqlx::Error> {
    let rows = sqlx::query_as!(
        ProviderKeyRow,
        r#"SELECT id as "id!", provider_id, created_at, api_key_ciphertext, api_key_nonce,
                  key_version
           FROM provider_key WHERE provider_id = ? ORDER BY created_at"#,
        provider_id,
    )
    .fetch_all(pool)
    .await?;
    rows.iter()
        .map(|r| r.to_model(kp).map_err(crypto_to_sqlx))
        .collect()
}

pub async fn delete_provider_key(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM provider_key WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — Tenant
// ---------------------------------------------------------------------------

/// Insert a tenant. `auth_url` is NOT NULL → inserting with an empty/non-null
/// value is fine; a NULL would error at the SQLite layer.
///
/// Empty/blank `cert_file`/`cert_key` strings are normalized to `NULL`:
/// optional legacy cert paths arrive as `""` from the admin UI (and other
/// clients) when left blank, and an empty string is not a path — persisting
/// it would poison `build_config`/TLS resolution and the legacy cert
/// conversion (see `apply_tenant_cert`).
pub async fn insert_tenant(pool: &SqlitePool, t: &Tenant) -> Result<(), sqlx::Error> {
    let cert_key = non_empty_path(t.cert_key.as_deref());
    let cert_file = non_empty_path(t.cert_file.as_deref());
    sqlx::query!(
        "INSERT INTO tenant (id, name, domain, auth_url, cert_key, cert_file, enabled, \
         created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
        t.id,
        t.name,
        t.domain,
        t.auth_url,
        cert_key,
        cert_file,
        t.enabled,
        t.created_at,
        t.updated_at,
    )
    .execute(pool)
    .await?;
    Ok(())
}

/// Blank certificate paths are stored as `NULL` (empty string is not a path).
fn non_empty_path(p: Option<&str>) -> Option<String> {
    p.map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_string)
}

pub async fn get_tenant(pool: &SqlitePool, id: &str) -> Result<Tenant, sqlx::Error> {
    let row = sqlx::query_as!(
        TenantRow,
        r#"SELECT id as "id!", name, domain, auth_url, cert_key, cert_file, enabled,
                  created_at, updated_at
           FROM tenant WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_tenants(pool: &SqlitePool) -> Result<Vec<Tenant>, sqlx::Error> {
    let rows = sqlx::query_as!(
        TenantRow,
        r#"SELECT id as "id!", name, domain, auth_url, cert_key, cert_file, enabled,
                  created_at, updated_at
           FROM tenant ORDER BY created_at"#
    )
    .fetch_all(pool)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

/// Update a tenant's mutable fields (`name`, `domain`, `auth_url`, cert paths,
/// `enabled`, `updated_at`). Blank cert paths are normalized to `NULL`
/// (same rule as `insert_tenant`).
pub async fn update_tenant(pool: &SqlitePool, t: &Tenant) -> Result<(), sqlx::Error> {
    let cert_key = non_empty_path(t.cert_key.as_deref());
    let cert_file = non_empty_path(t.cert_file.as_deref());
    sqlx::query!(
        "UPDATE tenant SET name = ?, domain = ?, auth_url = ?, cert_key = ?, cert_file = ?, \
         enabled = ?, updated_at = ? WHERE id = ?",
        t.name,
        t.domain,
        t.auth_url,
        cert_key,
        cert_file,
        t.enabled,
        t.updated_at,
        t.id,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn delete_tenant(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM tenant WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Tenant certificate content (migration 0007, cluster P0a)
// ---------------------------------------------------------------------------
//
// The cert is the tenant row itself: `cert_pem` (public, plaintext) +
// `cert_key_*` (AES-256-GCM sealed with the same master key as provider
// api-keys). The in-memory [`TenantCert`] carries the private key as
// plaintext only — it is decrypted at the DB boundary and never persisted or
// serialised.

/// Certificate content for one tenant, plaintext in memory.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TenantCert {
    pub tenant_id: String,
    /// Public cert PEM (`None` = no cert configured).
    pub cert_pem: Option<String>,
    /// Private key PEM, plaintext in memory only.
    pub cert_key_pem: Option<String>,
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct TenantCertRow {
    tenant_id: String,
    cert_pem: Option<String>,
    cert_key_ciphertext: Option<Vec<u8>>,
    cert_key_nonce: Option<Vec<u8>>,
    cert_key_version: Option<i64>,
}

impl TenantCertRow {
    /// Decrypt the sealed private key into a plaintext [`TenantCert`]. A row
    /// with ciphertext but a bad/missing nonce or version is a hard decode
    /// error (tampered / wrong master key — fail-closed, like provider keys).
    fn to_model(&self, kp: &dyn KeyProvider) -> Result<TenantCert, sqlx::Error> {
        let cert_key_pem = match (
            &self.cert_key_ciphertext,
            &self.cert_key_nonce,
            self.cert_key_version,
        ) {
            (Some(ct), Some(nonce), Some(version)) => {
                let nonce: [u8; crypto::NONCE_LEN] = nonce
                    .as_slice()
                    .try_into()
                    .map_err(|_| crypto_to_sqlx(CryptoError::Decrypt))?;
                let sealed = Sealed {
                    ciphertext: ct.clone(),
                    nonce,
                    key_version: version as u32,
                };
                let plaintext = kp.open(&sealed).map_err(crypto_to_sqlx)?;
                Some(
                    String::from_utf8(plaintext)
                        .map_err(|_| crypto_to_sqlx(CryptoError::NotUtf8))?,
                )
            }
            _ => None,
        };
        Ok(TenantCert {
            tenant_id: self.tenant_id.clone(),
            cert_pem: self.cert_pem.clone(),
            cert_key_pem,
        })
    }
}

/// Fetch one tenant's certificate content (`None` when the tenant is absent).
pub async fn get_tenant_cert(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    tenant_id: &str,
) -> Result<Option<TenantCert>, sqlx::Error> {
    let row = sqlx::query_as!(
        TenantCertRow,
        r#"SELECT id as "tenant_id!", cert_pem, cert_key_ciphertext, cert_key_nonce,
                  cert_key_version
           FROM tenant WHERE id = ?"#,
        tenant_id
    )
    .fetch_optional(pool)
    .await?;
    row.map(|r| r.to_model(kp)).transpose()
}

/// All tenants' certificate content (the loader overlays this onto the
/// path-based `certs` map, content-first).
pub async fn list_tenant_certs(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
) -> Result<Vec<TenantCert>, sqlx::Error> {
    let rows = sqlx::query_as!(
        TenantCertRow,
        r#"SELECT id as "tenant_id!", cert_pem, cert_key_ciphertext, cert_key_nonce,
                  cert_key_version
           FROM tenant ORDER BY id"#
    )
    .fetch_all(pool)
    .await?;
    rows.iter().map(|r| r.to_model(kp)).collect()
}

/// Write a tenant's certificate content. `None` fields clear the columns
/// (explicit cert removal). The private key is sealed at the DB boundary —
/// the caller passes plaintext, this function persists ciphertext only.
pub async fn update_tenant_cert(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    cert: &TenantCert,
) -> Result<(), sqlx::Error> {
    let (ct, nonce, version) = match &cert.cert_key_pem {
        Some(pem) => {
            let sealed = kp.seal(pem.as_bytes()).map_err(crypto_to_sqlx)?;
            (
                Some(sealed.ciphertext),
                Some(sealed.nonce.to_vec()),
                Some(sealed.key_version as i64),
            )
        }
        None => (None, None, None),
    };
    sqlx::query!(
        "UPDATE tenant SET cert_pem = ?, cert_key_ciphertext = ?, cert_key_nonce = ?, \
         cert_key_version = ? WHERE id = ?",
        cert.cert_pem,
        ct,
        nonce,
        version,
        cert.tenant_id,
    )
    .execute(pool)
    .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Tenant access token (migration 0009, self-service auth-cache invalidation)
// ---------------------------------------------------------------------------
//
// The tenant self-service credential is stored as a SHA-256 hex HASH only —
// one-way, never echoed, never recoverable (lost token => rotate via the
// admin API / UI). It is compared, never used for outbound calls, so a hash
// is the correct primitive (same reasoning as the AuthCache's api-key
// digests).

/// Set (or clear, `None`) a tenant's access-token hash.
pub async fn set_tenant_access_token_hash(
    pool: &SqlitePool,
    tenant_id: &str,
    hash: Option<&str>,
) -> Result<(), sqlx::Error> {
    sqlx::query!("UPDATE tenant SET access_token_hash = ? WHERE id = ?", hash, tenant_id)
        .execute(pool)
        .await?;
    Ok(())
}

/// All `(tenant_id, access_token_hash)` pairs — the tenant-token gate scans
/// these and compares the presented token's digest (constant-time).
pub async fn list_tenant_access_token_hashes(
    pool: &SqlitePool,
) -> Result<Vec<(String, String)>, sqlx::Error> {
    let rows = sqlx::query!("SELECT id, access_token_hash FROM tenant WHERE access_token_hash IS NOT NULL")
        .fetch_all(pool)
        .await?;
    Ok(rows
        .into_iter()
        // `id` is `TEXT PRIMARY KEY` without NOT NULL, so sqlx types it
        // Option<String> — a PK can never be NULL, unwrap_or_default is safe.
        .filter_map(|r| r.access_token_hash.map(|h| (r.id.unwrap_or_default(), h)))
        .collect())
}

/// Whether a tenant has an access token configured (for the admin view).
pub async fn tenant_has_access_token(
    pool: &SqlitePool,
    tenant_id: &str,
) -> Result<bool, sqlx::Error> {
    let row = sqlx::query!("SELECT access_token_hash FROM tenant WHERE id = ?", tenant_id)
        .fetch_optional(pool)
        .await?;
    Ok(row.and_then(|r| r.access_token_hash).is_some())
}

/// One-time backfill for migration 0007: tenants with legacy `cert_file` /
/// `cert_key` paths but no stored content get their files read on this node
/// and stored as content (so the DB becomes self-contained and the shared
/// cert volume can be dropped). Best-effort: a failure is logged per tenant
/// and never aborts startup — the path fallback keeps serving until the files
/// become readable or the operator re-enters the cert via the admin API.
pub async fn backfill_legacy_certs(pool: &SqlitePool, kp: &dyn KeyProvider) {
    let tenants = match list_tenants(pool).await {
        Ok(t) => t,
        Err(e) => {
            tracing::warn!(error = %e, "cert backfill: list_tenants failed; skipping");
            return;
        }
    };
    let existing = match list_tenant_certs(pool, kp).await {
        Ok(c) => c,
        Err(e) => {
            tracing::warn!(error = %e, "cert backfill: list_tenant_certs failed; skipping");
            return;
        }
    };
    let with_content: std::collections::HashSet<&str> = existing
        .iter()
        .filter(|c| c.cert_pem.is_some())
        .map(|c| c.tenant_id.as_str())
        .collect();

    for t in tenants {
        if with_content.contains(t.id.as_str()) {
            continue;
        }
        let (Some(cert_path), Some(key_path)) = (&t.cert_file, &t.cert_key) else {
            continue;
        };
        let (Ok(cert_bytes), Ok(key_bytes)) = (std::fs::read(cert_path), std::fs::read(key_path))
        else {
            tracing::warn!(
                tenant = %t.id,
                cert_path,
                key_path,
                "cert backfill: legacy cert paths not readable on this node; path fallback remains active"
            );
            continue;
        };
        let cert = TenantCert {
            tenant_id: t.id.clone(),
            cert_pem: Some(String::from_utf8_lossy(&cert_bytes).into_owned()),
            cert_key_pem: Some(String::from_utf8_lossy(&key_bytes).into_owned()),
        };
        match update_tenant_cert(pool, kp, &cert).await {
            Ok(()) => tracing::info!(tenant = %t.id, "cert backfill: legacy paths -> content"),
            Err(e) => tracing::warn!(tenant = %t.id, error = %e, "cert backfill: store failed"),
        }
    }
}

// ---------------------------------------------------------------------------
// CRUD — TenantProvider
// ---------------------------------------------------------------------------

pub async fn insert_tenant_provider(
    pool: &SqlitePool,
    tp: &TenantProvider,
) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "INSERT INTO tenant_provider (id, tenant_id, provider_id) VALUES (?, ?, ?)",
        tp.id,
        tp.tenant_id,
        tp.provider_id,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_tenant_provider(
    pool: &SqlitePool,
    id: &str,
) -> Result<TenantProvider, sqlx::Error> {
    let row = sqlx::query_as!(
        TenantProviderRow,
        r#"SELECT id as "id!", tenant_id, provider_id
           FROM tenant_provider WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_tenant_providers(pool: &SqlitePool) -> Result<Vec<TenantProvider>, sqlx::Error> {
    let rows = sqlx::query_as!(
        TenantProviderRow,
        r#"SELECT id as "id!", tenant_id, provider_id
           FROM tenant_provider ORDER BY tenant_id, provider_id"#
    )
    .fetch_all(pool)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

pub async fn delete_tenant_provider(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM tenant_provider WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — TenantModel
// ---------------------------------------------------------------------------

pub async fn insert_tenant_model(pool: &SqlitePool, tm: &TenantModel) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "INSERT INTO tenant_model (id, tenant_id, model_key) VALUES (?, ?, ?)",
        tm.id,
        tm.tenant_id,
        tm.model_key,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_tenant_model(pool: &SqlitePool, id: &str) -> Result<TenantModel, sqlx::Error> {
    let row = sqlx::query_as!(
        TenantModelRow,
        r#"SELECT id as "id!", tenant_id, model_key
           FROM tenant_model WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_tenant_models(pool: &SqlitePool) -> Result<Vec<TenantModel>, sqlx::Error> {
    let rows = sqlx::query_as!(
        TenantModelRow,
        r#"SELECT id as "id!", tenant_id, model_key
           FROM tenant_model ORDER BY tenant_id, model_key"#
    )
    .fetch_all(pool)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

pub async fn delete_tenant_model(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM tenant_model WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — LimitRole
// ---------------------------------------------------------------------------

pub async fn insert_limit_role(pool: &SqlitePool, r: &LimitRole) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "INSERT INTO limit_role (id, name, matching_key, matching_model, matching_tenant, \
         matching_provider, limit_count, limit_token, window, enabled, created_at) \
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        r.id,
        r.name,
        r.matching_key,
        r.matching_model,
        r.matching_tenant,
        r.matching_provider,
        r.limit_count,
        r.limit_token,
        r.window,
        r.enabled,
        r.created_at,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_limit_role(pool: &SqlitePool, id: &str) -> Result<LimitRole, sqlx::Error> {
    let row = sqlx::query_as!(
        LimitRoleRow,
        r#"SELECT id as "id!", name, matching_key, matching_model, matching_tenant,
                  matching_provider, limit_count, limit_token, window, enabled, created_at
           FROM limit_role WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_limit_roles(pool: &SqlitePool) -> Result<Vec<LimitRole>, sqlx::Error> {
    let rows = sqlx::query_as!(
        LimitRoleRow,
        r#"SELECT id as "id!", name, matching_key, matching_model, matching_tenant,
                  matching_provider, limit_count, limit_token, window, enabled, created_at
           FROM limit_role ORDER BY created_at"#
    )
    .fetch_all(pool)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

/// Update a limit role's mutable fields.
pub async fn update_limit_role(pool: &SqlitePool, r: &LimitRole) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "UPDATE limit_role SET name = ?, matching_key = ?, matching_model = ?, \
         matching_tenant = ?, matching_provider = ?, limit_count = ?, limit_token = ?, \
         window = ?, enabled = ? WHERE id = ?",
        r.name,
        r.matching_key,
        r.matching_model,
        r.matching_tenant,
        r.matching_provider,
        r.limit_count,
        r.limit_token,
        r.window,
        r.enabled,
        r.id,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn delete_limit_role(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM limit_role WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — provider_key_binding (design §7.1b)
// ---------------------------------------------------------------------------

/// Insert a binding. Violating the UNIQUE `key_prefix` constraint returns a
/// sqlx UNIQUE violation (→ 409 by the admin layer).
pub async fn insert_provider_key_binding(
    pool: &SqlitePool,
    b: &ProviderKeyBinding,
) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "INSERT INTO provider_key_binding (id, key_prefix, provider_id, enabled, created_at, \
         updated_at) VALUES (?, ?, ?, ?, ?, ?)",
        b.id,
        b.key_prefix,
        b.provider_id,
        b.enabled,
        b.created_at,
        b.updated_at
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_provider_key_binding(
    pool: &SqlitePool,
    id: &str,
) -> Result<ProviderKeyBinding, sqlx::Error> {
    let row = sqlx::query_as!(
        ProviderKeyBindingRow,
        r#"SELECT id as "id!", key_prefix, provider_id, enabled, created_at, updated_at
           FROM provider_key_binding WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_provider_key_bindings(
    pool: &SqlitePool,
) -> Result<Vec<ProviderKeyBinding>, sqlx::Error> {
    let rows = sqlx::query_as!(
        ProviderKeyBindingRow,
        r#"SELECT id as "id!", key_prefix, provider_id, enabled, created_at, updated_at
           FROM provider_key_binding ORDER BY key_prefix"#
    )
    .fetch_all(pool)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

/// Update a binding's mutable fields (prefix / provider / enabled).
pub async fn update_provider_key_binding(
    pool: &SqlitePool,
    b: &ProviderKeyBinding,
) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "UPDATE provider_key_binding SET key_prefix = ?, provider_id = ?, enabled = ?, \
         updated_at = ? WHERE id = ?",
        b.key_prefix,
        b.provider_id,
        b.enabled,
        b.updated_at,
        b.id
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn delete_provider_key_binding(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM provider_key_binding WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Config version metadata + full-table config restore (cluster P1/P2)
// ---------------------------------------------------------------------------
//
// `config_meta` (migration 0008) holds control-plane bookkeeping; today the
// standby replica's last-applied `config_version`. `restore_config` rebuilds
// every config table from a snapshot in ONE transaction (standby replica
// materialization, cluster P2) so a crash mid-restore never leaves a
// half-config. It uses runtime-checked `sqlx::query` (like the sinks): the
// statements run against a live migration-pinned DB and the tables are tiny.

/// The stored last-applied config version (`None` when never set).
pub async fn get_config_version(pool: &SqlitePool) -> Result<Option<u64>, sqlx::Error> {
    let row: Option<(String,)> =
        sqlx::query_as("SELECT value FROM config_meta WHERE key = 'config_version'")
            .fetch_optional(pool)
            .await?;
    Ok(row.and_then(|(v,)| v.parse().ok()))
}

/// Persist the last-applied config version (upsert).
pub async fn set_config_version(pool: &SqlitePool, version: u64) -> Result<(), sqlx::Error> {
    sqlx::query(
        "INSERT INTO config_meta (key, value) VALUES ('config_version', ?) \
         ON CONFLICT(key) DO UPDATE SET value = excluded.value",
    )
    .bind(version.to_string())
    .execute(pool)
    .await?;
    Ok(())
}

/// Rebuild every config table from `cfg` (+ the fidelity rows) in a single
/// transaction. Secrets are re-sealed at this boundary with `kp`.
///
/// Table order: parents first on insert (FK), children first on delete.
pub async fn restore_config(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    cfg: &hydra_core::config::ConfigData,
    provider_models: &[hydra_core::model::ProviderModel],
    tenant_providers: &[hydra_core::model::TenantProvider],
    tenant_models: &[hydra_core::model::TenantModel],
) -> Result<(), sqlx::Error> {
    let mut tx = pool.begin().await?;

    // Wipe children before parents.
    for table in [
        "provider_key_binding",
        "limit_role",
        "tenant_model",
        "tenant_provider",
        "tenant",
        "provider_key",
        "provider_model",
        "provider",
    ] {
        sqlx::query(&format!("DELETE FROM {table}"))
            .execute(&mut *tx)
            .await?;
    }

    // Providers.
    for p in cfg.providers.values() {
        sqlx::query(
            "INSERT INTO provider (id, key, name, endpoint, weight, created_at, updated_at, \
             max_concurrency, max_queue_depth, queue_wait_timeout_ms) \
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        )
        .bind(&p.id)
        .bind(&p.key)
        .bind(&p.name)
        .bind(&p.endpoint)
        .bind(p.weight)
        .bind(&p.created_at)
        .bind(&p.updated_at)
        .bind(p.max_concurrency.map(|v| v as i64))
        .bind(p.max_queue_depth.map(|v| v as i64))
        .bind(p.queue_wait_timeout_ms.map(|v| v as i64))
        .execute(&mut *tx)
        .await?;
    }

    // Provider models (fidelity rows — includes offline models).
    for m in provider_models {
        sqlx::query(
            "INSERT INTO provider_model (id, key, name, provider_id, status) \
             VALUES (?, ?, ?, ?, ?)",
        )
        .bind(&m.id)
        .bind(&m.key)
        .bind(&m.name)
        .bind(&m.provider_id)
        .bind(m.status)
        .execute(&mut *tx)
        .await?;
    }

    // Provider keys (sealed at the boundary).
    for (provider_id, keys) in &cfg.provider_keys {
        for api_key in keys {
            let sealed = kp.seal(api_key.as_bytes()).map_err(crypto_to_sqlx)?;
            let nonce: &[u8] = &sealed.nonce;
            sqlx::query(
                "INSERT INTO provider_key (id, provider_id, api_key_ciphertext, api_key_nonce, \
                 key_version, created_at) VALUES (?, ?, ?, ?, ?, ?)",
            )
            .bind(gen_id_static())
            .bind(provider_id)
            .bind(sealed.ciphertext)
            .bind(nonce)
            .bind(sealed.key_version as i64)
            .bind(now_static())
            .execute(&mut *tx)
            .await?;
        }
    }

    // Tenants (+ cert content columns).
    for t in cfg.tenants_by_domain.values() {
        sqlx::query(
            "INSERT INTO tenant (id, name, domain, auth_url, cert_key, cert_file, enabled, \
             created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
        )
        .bind(&t.id)
        .bind(&t.name)
        .bind(&t.domain)
        .bind(&t.auth_url)
        .bind(&t.cert_key)
        .bind(&t.cert_file)
        .bind(t.enabled)
        .bind(&t.created_at)
        .bind(&t.updated_at)
        .execute(&mut *tx)
        .await?;
        // Cert content (migration 0007): sealed key, plaintext cert PEM.
        let cert_meta = cfg.certs.get(&t.domain.to_lowercase());
        if let Some(cm) = cert_meta {
            if let Some(cert_pem) = &cm.cert_pem {
                let (ct, nonce, version) = match &cm.cert_key_pem {
                    Some(pem) => {
                        let sealed = kp.seal(pem.as_bytes()).map_err(crypto_to_sqlx)?;
                        (
                            Some(sealed.ciphertext),
                            Some(sealed.nonce.to_vec()),
                            Some(sealed.key_version as i64),
                        )
                    }
                    None => (None, None, None),
                };
                sqlx::query(
                    "UPDATE tenant SET cert_pem = ?, cert_key_ciphertext = ?, \
                     cert_key_nonce = ?, cert_key_version = ? WHERE id = ?",
                )
                .bind(cert_pem)
                .bind(ct)
                .bind(nonce)
                .bind(version)
                .bind(&t.id)
                .execute(&mut *tx)
                .await?;
            }
        }
    }

    // Tenant provider / model grants (fidelity rows — ids preserved).
    for tp in tenant_providers {
        sqlx::query("INSERT INTO tenant_provider (id, tenant_id, provider_id) VALUES (?, ?, ?)")
            .bind(&tp.id)
            .bind(&tp.tenant_id)
            .bind(&tp.provider_id)
            .execute(&mut *tx)
            .await?;
    }
    for tm in tenant_models {
        sqlx::query("INSERT INTO tenant_model (id, tenant_id, model_key) VALUES (?, ?, ?)")
            .bind(&tm.id)
            .bind(&tm.tenant_id)
            .bind(&tm.model_key)
            .execute(&mut *tx)
            .await?;
    }

    // Limit roles.
    for r in &cfg.limit_roles {
        sqlx::query(
            "INSERT INTO limit_role (id, name, matching_key, matching_model, matching_tenant, \
             matching_provider, limit_count, limit_token, window, enabled, created_at) \
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        )
        .bind(&r.id)
        .bind(&r.name)
        .bind(&r.matching_key)
        .bind(&r.matching_model)
        .bind(&r.matching_tenant)
        .bind(&r.matching_provider)
        .bind(r.limit_count)
        .bind(r.limit_token)
        .bind(&r.window)
        .bind(r.enabled)
        .bind(&r.created_at)
        .execute(&mut *tx)
        .await?;
    }

    // api-key prefix bindings.
    for b in &cfg.key_prefix_bindings {
        sqlx::query(
            "INSERT INTO provider_key_binding (id, key_prefix, provider_id, enabled, created_at, \
             updated_at) VALUES (?, ?, ?, ?, ?, ?)",
        )
        .bind(&b.id)
        .bind(&b.key_prefix)
        .bind(&b.provider_id)
        .bind(b.enabled)
        .bind(&b.created_at)
        .bind(&b.updated_at)
        .execute(&mut *tx)
        .await?;
    }

    tx.commit().await?;
    Ok(())
}

/// `gen_id`-style id for restore (provider keys need fresh ids). Mirrors the
/// admin handler helper without depending on it.
fn gen_id_static() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    format!("id-{nanos:x}")
}

/// `now_ts`-style timestamp for restore.
fn now_static() -> String {
    chrono::Utc::now().format("%Y-%m-%d %H:%M:%S").to_string()
}
