//! sqlx `SqlitePool`, PRAGMA setup (design §15.2), `sqlx::migrate!` embedding,
//! and the repo CRUD layer (thin wrappers over **compile-time-checked** sqlx
//! `query!`/`query_as!` macros).
//!
//! ## Compile-time SQL validation
//!
//! Every query in this module uses `sqlx::query!` / `sqlx::query_as!`, which
//! validate the SQL text, column names, column types, and bind-parameter types
//! against the committed `.sqlx/` offline cache at **compile time**. This
//! catches schema drift before the code can even build.
//!
//! The `.sqlx/` cache is generated by `cargo sqlx prepare` against a fully
//! migrated reference database (see the project README / CI). CI sets
//! `SQLX_OFFLINE=true` so no live `DATABASE_URL` is needed during builds.
//!
//! Repo functions map the SQLite `INTEGER` columns onto `i64` in the row
//! structs (sqlx decodes `INTEGER` → `i64`) and cast to the idiomatic `i32` /
//! `bool` used by [`hydra_core::model`] at the boundary.

use std::str::FromStr;
use std::time::Duration;

use sqlx::migrate::MigrateError;
use sqlx::sqlite::{SqliteConnectOptions, SqliteJournalMode, SqlitePoolOptions, SqliteSynchronous};
use sqlx::SqlitePool;

use hydra_core::model::{
    LimitRole, Provider, ProviderKey, ProviderKeyBinding, ProviderModel, SubTenant, SubTenantRoute,
    Tenant, TenantModel, TenantProvider,
};

use crate::crypto::{self, CryptoError, KeyProvider, Sealed};

// ---------------------------------------------------------------------------
// Pool initialisation + PRAGMAs (design §15.2)
// ---------------------------------------------------------------------------

/// Connect a `SqlitePool` and apply the production PRAGMAs (design §15.2):
/// `journal_mode=WAL`, `synchronous=NORMAL`, `busy_timeout=5000`,
/// `foreign_keys=ON`, `mmap_size=134217728`.
///
/// PRAGMAs are applied **per connection** via [`SqliteConnectOptions`]:
/// `foreign_keys` is connection-scoped in SQLite, so a one-shot
/// `PRAGMA foreign_keys=ON` on a single connection would not propagate to the
/// rest of the pool — the connect-options builder applies it to every fresh
/// connection, which is the root-cause-correct approach for a multi-connection
/// file-backed production pool.
///
/// For `:memory:` URLs the pool is pinned to a single connection: each
/// in-memory connection is otherwise an isolated empty database, so a pool
/// with more than one connection would make migrations invisible to other
/// connections (the canonical sqlx in-memory test pattern).
pub async fn init_pool(url: &str) -> Result<SqlitePool, sqlx::Error> {
    let opts = SqliteConnectOptions::from_str(url)?
        .journal_mode(SqliteJournalMode::Wal)
        .synchronous(SqliteSynchronous::Normal)
        .busy_timeout(Duration::from_millis(5000))
        .foreign_keys(true)
        .pragma("mmap_size", "134217728");

    let is_memory = url.contains(":memory:");
    let pool = SqlitePoolOptions::new()
        .max_connections(if is_memory { 1 } else { 8 })
        .connect_with(opts)
        .await?;
    Ok(pool)
}

/// Run the embedded migrations (`sqlx::migrate!("./migrations")`).
pub async fn run_migrate(pool: &SqlitePool) -> Result<(), MigrateError> {
    sqlx::migrate!("./migrations").run(pool).await
}

/// Begin a transaction that takes SQLite's **write lock immediately**
/// (`BEGIN IMMEDIATE`) — use this for EVERY transaction that reads before it
/// writes, which is all of them here.
///
/// Why this exists: SQLite's plain `BEGIN` is DEFERRED. The transaction starts as
/// a reader and upgrades to a writer on its first write. Under WAL, if any other
/// connection commits between this transaction's first read and that upgrade,
/// the upgrade fails immediately with `SQLITE_BUSY` **without consulting
/// `busy_timeout`** — the reader's snapshot is stale, so waiting cannot help.
/// `init_pool` sets `busy_timeout(5000)`, but for a read-then-write transaction
/// that timeout never got a chance to apply: a perfectly ordinary concurrent
/// write (a usage-sink flush, another admin write) turned one of the two into a
/// `500 database_error`, and the "PUT-upsert converges at the quota boundary"
/// contract in `admin::sub_tenant_write` into a coin flip.
///
/// `BEGIN IMMEDIATE` asks for the write lock up front, where `busy_timeout` DOES
/// apply, so concurrent writers queue instead of colliding. The cost is that
/// writers serialize a little earlier; for a config-plane workload (a handful of
/// admin writes against a pool of 8) that is the correct trade.
pub async fn begin_write(
    pool: &SqlitePool,
) -> Result<sqlx::Transaction<'static, sqlx::Sqlite>, sqlx::Error> {
    pool.begin_with("BEGIN IMMEDIATE").await
}

// ---------------------------------------------------------------------------
// Row structs (mirror SQLite types) + conversions to core entities.
// ---------------------------------------------------------------------------

#[derive(sqlx::FromRow, Debug, Clone)]
struct ProviderRow {
    id: String,
    key: String,
    name: String,
    endpoint: String,
    weight: i64,
    created_at: String,
    updated_at: String,
    /// Per-provider concurrency admission policy (design-admission-queue §5).
    /// Nullable: NULL ⇒ use ProxyConfig defaults (opt-in). SQLite INTEGER → i64.
    max_concurrency: Option<i64>,
    max_queue_depth: Option<i64>,
    queue_wait_timeout_ms: Option<i64>,
}

/// Cast a nullable SQLite INTEGER (decoded as `Option<i64>`) to `Option<u32>`,
/// rejecting negative values (defensive — a manual DB edit should not panic the
/// loader). Negative ⇒ `None` (treated as "use defaults").
fn to_u32_opt(v: Option<i64>) -> Option<u32> {
    v.filter(|n| *n >= 0).map(|n| n as u32)
}

/// Same as [`to_u32_opt`] but for `u64` (`queue_wait_timeout_ms`).
fn to_u64_opt(v: Option<i64>) -> Option<u64> {
    v.filter(|n| *n >= 0).map(|n| n as u64)
}

impl From<ProviderRow> for Provider {
    fn from(r: ProviderRow) -> Self {
        Provider {
            id: r.id,
            key: r.key,
            name: r.name,
            endpoint: r.endpoint,
            weight: r.weight as i32,
            created_at: r.created_at,
            updated_at: r.updated_at,
            max_concurrency: to_u32_opt(r.max_concurrency),
            max_queue_depth: to_u32_opt(r.max_queue_depth),
            queue_wait_timeout_ms: to_u64_opt(r.queue_wait_timeout_ms),
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct ProviderModelRow {
    id: String,
    key: String,
    name: String,
    provider_id: String,
    status: i64,
}

impl From<ProviderModelRow> for ProviderModel {
    fn from(r: ProviderModelRow) -> Self {
        ProviderModel {
            id: r.id,
            key: r.key,
            name: r.name,
            provider_id: r.provider_id,
            status: r.status as i32,
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct ProviderKeyRow {
    id: String,
    provider_id: String,
    // Nullable in the schema (ALTER TABLE ADD COLUMN BLOB has no NOT NULL), but
    // always populated by `insert_provider_key`. The `query_as!` macro enforces
    // nullability at compile time, so these are Option and unwrapped in to_model.
    api_key_ciphertext: Option<Vec<u8>>,
    api_key_nonce: Option<Vec<u8>>,
    key_version: i64,
    created_at: String,
}

impl ProviderKeyRow {
    /// Decrypt the ciphertext into a plaintext `ProviderKey` model. Plaintext
    /// exists only transiently here, then lives in-memory in the model (never
    /// persisted). Requires a [`KeyProvider`] because decryption is I/O on the
    /// master key.
    fn to_model(&self, kp: &dyn KeyProvider) -> Result<ProviderKey, CryptoError> {
        let ciphertext = self
            .api_key_ciphertext
            .as_ref()
            .ok_or(CryptoError::Decrypt)?;
        let nonce_bytes = self.api_key_nonce.as_ref().ok_or(CryptoError::Decrypt)?;
        let nonce: [u8; crypto::NONCE_LEN] = nonce_bytes
            .as_slice()
            .try_into()
            .map_err(|_| CryptoError::Decrypt)?;
        let sealed = Sealed {
            ciphertext: ciphertext.clone(),
            nonce,
            key_version: self.key_version as u32,
        };
        let plaintext = kp.open(&sealed)?;
        let api_key = String::from_utf8(plaintext).map_err(|_| CryptoError::NotUtf8)?;
        Ok(ProviderKey {
            id: self.id.clone(),
            provider_id: self.provider_id.clone(),
            api_key,
            created_at: self.created_at.clone(),
        })
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct TenantRow {
    id: String,
    name: String,
    domain: String,
    auth_url: String,
    cert_key: Option<String>,
    cert_file: Option<String>,
    enabled: i64,
    created_at: String,
    updated_at: String,
}

impl From<TenantRow> for Tenant {
    fn from(r: TenantRow) -> Self {
        Tenant {
            id: r.id,
            name: r.name,
            domain: r.domain,
            auth_url: r.auth_url,
            cert_key: r.cert_key,
            cert_file: r.cert_file,
            enabled: r.enabled != 0,
            created_at: r.created_at,
            updated_at: r.updated_at,
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct TenantProviderRow {
    id: String,
    tenant_id: String,
    provider_id: String,
}

impl From<TenantProviderRow> for TenantProvider {
    fn from(r: TenantProviderRow) -> Self {
        TenantProvider {
            id: r.id,
            tenant_id: r.tenant_id,
            provider_id: r.provider_id,
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct TenantModelRow {
    id: String,
    tenant_id: String,
    model_key: String,
}

impl From<TenantModelRow> for TenantModel {
    fn from(r: TenantModelRow) -> Self {
        TenantModel {
            id: r.id,
            tenant_id: r.tenant_id,
            model_key: r.model_key,
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct LimitRoleRow {
    id: String,
    name: String,
    matching_key: Option<String>,
    matching_model: Option<String>,
    matching_tenant: Option<String>,
    matching_provider: Option<String>,
    limit_count: Option<i64>,
    limit_token: Option<i64>,
    window: String,
    enabled: i64,
    created_at: String,
}

impl LimitRoleRow {
    /// The in-memory row, with `matching_key` opened.
    ///
    /// # Errors
    /// [`crypto_to_sqlx`] wrapping a [`CryptoError`] when the stored value IS a sealed envelope the
    /// master key cannot open (a wrong or rotated-away key is refused, never handed back as a key).
    /// A value that is not an envelope at all is a pre-D-16 plaintext row and is returned as-is —
    /// see `crypto::Sealed::open_text`.
    fn to_model(&self, kp: &dyn KeyProvider) -> Result<LimitRole, sqlx::Error> {
        Ok(LimitRole {
            id: self.id.clone(),
            name: self.name.clone(),
            matching_key: open_limit_key(kp, self.matching_key.clone())?,
            matching_model: self.matching_model.clone(),
            matching_tenant: self.matching_tenant.clone(),
            matching_provider: self.matching_provider.clone(),
            limit_count: self.limit_count,
            limit_token: self.limit_token,
            window: self.window.clone(),
            enabled: self.enabled != 0,
            created_at: self.created_at.clone(),
        })
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct ProviderKeyBindingRow {
    id: String,
    key_prefix: String,
    provider_id: String,
    enabled: i64,
    created_at: String,
    updated_at: String,
}

impl From<ProviderKeyBindingRow> for ProviderKeyBinding {
    fn from(r: ProviderKeyBindingRow) -> Self {
        ProviderKeyBinding {
            id: r.id,
            key_prefix: r.key_prefix,
            provider_id: r.provider_id,
            enabled: r.enabled != 0,
            created_at: r.created_at,
            updated_at: r.updated_at,
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct SubTenantRow {
    id: String,
    tenant_id: String,
    name: String,
    key_prefix: String,
    enabled: i64,
    created_at: String,
    updated_at: String,
}

impl From<SubTenantRow> for SubTenant {
    fn from(r: SubTenantRow) -> Self {
        SubTenant {
            id: r.id,
            tenant_id: r.tenant_id,
            name: r.name,
            key_prefix: r.key_prefix,
            enabled: r.enabled != 0,
            created_at: r.created_at,
            updated_at: r.updated_at,
        }
    }
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct SubTenantRouteRow {
    id: String,
    sub_tenant_id: String,
    model_key: Option<String>,
    provider_id: String,
    enabled: i64,
    created_at: String,
    updated_at: String,
}

impl From<SubTenantRouteRow> for SubTenantRoute {
    fn from(r: SubTenantRouteRow) -> Self {
        SubTenantRoute {
            id: r.id,
            sub_tenant_id: r.sub_tenant_id,
            model_key: r.model_key,
            provider_id: r.provider_id,
            enabled: r.enabled != 0,
            created_at: r.created_at,
            updated_at: r.updated_at,
        }
    }
}

// ---------------------------------------------------------------------------
// CRUD — Provider
// ---------------------------------------------------------------------------

/// Insert a provider. Violating the UNIQUE `key` constraint returns
/// [`sqlx::Error::Database`] (UNIQUE violation).
pub async fn insert_provider(pool: &SqlitePool, p: &Provider) -> Result<(), sqlx::Error> {
    // Bind Option conversions to locals so the temporaries live long enough
    // for the sqlx macro's borrow checker.
    let max_concurrency = p.max_concurrency.map(|v| v as i64);
    let max_queue_depth = p.max_queue_depth.map(|v| v as i64);
    let queue_wait_timeout_ms = p.queue_wait_timeout_ms.map(|v| v as i64);
    sqlx::query!(
        "INSERT INTO provider (id, key, name, endpoint, weight, created_at, updated_at, \
         max_concurrency, max_queue_depth, queue_wait_timeout_ms) \
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        p.id,
        p.key,
        p.name,
        p.endpoint,
        p.weight,
        p.created_at,
        p.updated_at,
        max_concurrency,
        max_queue_depth,
        queue_wait_timeout_ms,
    )
    .execute(pool)
    .await?;
    Ok(())
}

/// Fetch a single provider by id; `Err(RowNotFound)` when absent.
pub async fn get_provider(pool: &SqlitePool, id: &str) -> Result<Provider, sqlx::Error> {
    let row = sqlx::query_as!(
        ProviderRow,
        r#"SELECT id as "id!", key, name, endpoint, weight, created_at, updated_at,
                  max_concurrency, max_queue_depth, queue_wait_timeout_ms
           FROM provider WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

/// All providers, ordered by `created_at`.
pub async fn list_providers(pool: &SqlitePool) -> Result<Vec<Provider>, sqlx::Error> {
    let rows = sqlx::query_as!(
        ProviderRow,
        r#"SELECT id as "id!", key, name, endpoint, weight, created_at, updated_at,
                  max_concurrency, max_queue_depth, queue_wait_timeout_ms
           FROM provider ORDER BY created_at"#
    )
    .fetch_all(pool)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

/// Update a provider's mutable fields.
pub async fn update_provider(pool: &SqlitePool, p: &Provider) -> Result<(), sqlx::Error> {
    let max_concurrency = p.max_concurrency.map(|v| v as i64);
    let max_queue_depth = p.max_queue_depth.map(|v| v as i64);
    let queue_wait_timeout_ms = p.queue_wait_timeout_ms.map(|v| v as i64);
    sqlx::query!(
        "UPDATE provider SET key = ?, name = ?, endpoint = ?, weight = ?, updated_at = ?, \
         max_concurrency = ?, max_queue_depth = ?, queue_wait_timeout_ms = ? \
         WHERE id = ?",
        p.key,
        p.name,
        p.endpoint,
        p.weight,
        p.updated_at,
        max_concurrency,
        max_queue_depth,
        queue_wait_timeout_ms,
        p.id,
    )
    .execute(pool)
    .await?;
    Ok(())
}

/// Delete a provider (CASCADE removes its models/keys and tenant_provider links).
pub async fn delete_provider(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM provider WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — ProviderModel
// ---------------------------------------------------------------------------

/// Insert a provider model. The CHECK (`status IN (1,0,-1)`) and
/// UNIQUE(`key`,`provider_id`) constraints are enforced by SQLite.
pub async fn insert_provider_model(
    pool: &SqlitePool,
    m: &ProviderModel,
) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "INSERT INTO provider_model (id, key, name, provider_id, status) VALUES (?, ?, ?, ?, ?)",
        m.id,
        m.key,
        m.name,
        m.provider_id,
        m.status,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_provider_model(pool: &SqlitePool, id: &str) -> Result<ProviderModel, sqlx::Error> {
    let row = sqlx::query_as!(
        ProviderModelRow,
        r#"SELECT id as "id!", key, name, provider_id, status
           FROM provider_model WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_provider_models(pool: &SqlitePool) -> Result<Vec<ProviderModel>, sqlx::Error> {
    list_provider_models_on(pool).await
}

/// [`list_provider_models`] on an arbitrary executor (one-transaction read).
pub(crate) async fn list_provider_models_on<'e, E>(
    exec: E,
) -> Result<Vec<ProviderModel>, sqlx::Error>
where
    E: sqlx::Executor<'e, Database = sqlx::Sqlite>,
{
    let rows = sqlx::query_as!(
        ProviderModelRow,
        r#"SELECT id as "id!", key, name, provider_id, status
           FROM provider_model ORDER BY key, provider_id"#
    )
    .fetch_all(exec)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

/// Update a provider model's mutable fields (`key`, `name`, `status`).
pub async fn update_provider_model(
    pool: &SqlitePool,
    m: &ProviderModel,
) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "UPDATE provider_model SET key = ?, name = ?, status = ? WHERE id = ?",
        m.key,
        m.name,
        m.status,
        m.id,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn delete_provider_model(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM provider_model WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — ProviderKey
// ---------------------------------------------------------------------------

/// Map a [`CryptoError`] into a sqlx error so the repo functions keep a single
/// `Result<_, sqlx::Error>` return type. `CryptoError` is `Send + Sync + Error`.
fn crypto_to_sqlx(e: CryptoError) -> sqlx::Error {
    sqlx::Error::Decode(Box::new(e))
}

pub async fn insert_provider_key(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    k: &ProviderKey,
) -> Result<(), sqlx::Error> {
    let sealed = kp.seal(k.api_key.as_bytes()).map_err(crypto_to_sqlx)?;
    let nonce: &[u8] = &sealed.nonce;
    sqlx::query!(
        "INSERT INTO provider_key (id, provider_id, api_key_ciphertext, api_key_nonce, \
         key_version, created_at) VALUES (?, ?, ?, ?, ?, ?)",
        k.id,
        k.provider_id,
        sealed.ciphertext,
        nonce,
        sealed.key_version,
        k.created_at,
    )
    .execute(pool)
    .await?;
    Ok(())
}

/// Atomic provider-key upsert, used by `PUT /api/v1/provider-keys/{id}`.
///
/// The admin PUT was a bare `DELETE` + `INSERT` with the delete error thrown
/// away. `provider_key.provider_id` is a `REFERENCES provider(id)` FK, so a
/// body naming a provider that does not exist made the **insert** fail *after*
/// the old, working key had already been deleted: the API answered 400/4xx, the
/// operator believed the update had simply failed, and the provider was left
/// with no key at all (`NoAvailableKey` 503) until someone noticed (audit
/// §3.15).
///
/// Both statements now run in one transaction: a failing insert rolls the delete
/// back and the previous key survives intact. Reuses the exact SQL text of
/// `insert_provider_key` / `delete_provider_key`, so the `.sqlx` offline
/// cache needs no regeneration.
pub async fn upsert_provider_key(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    k: &ProviderKey,
) -> Result<(), sqlx::Error> {
    let sealed = kp.seal(k.api_key.as_bytes()).map_err(crypto_to_sqlx)?;
    let nonce: &[u8] = &sealed.nonce;
    let mut tx = begin_write(pool).await?;
    sqlx::query!("DELETE FROM provider_key WHERE id = ?", k.id)
        .execute(&mut *tx)
        .await?;
    sqlx::query!(
        "INSERT INTO provider_key (id, provider_id, api_key_ciphertext, api_key_nonce, \
         key_version, created_at) VALUES (?, ?, ?, ?, ?, ?)",
        k.id,
        k.provider_id,
        sealed.ciphertext,
        nonce,
        sealed.key_version,
        k.created_at,
    )
    .execute(&mut *tx)
    .await?;
    tx.commit().await?;
    Ok(())
}

pub async fn get_provider_key(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    id: &str,
) -> Result<ProviderKey, sqlx::Error> {
    let row = sqlx::query_as!(
        ProviderKeyRow,
        r#"SELECT id as "id!", provider_id, created_at, api_key_ciphertext, api_key_nonce,
                  key_version
           FROM provider_key WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    row.to_model(kp).map_err(crypto_to_sqlx)
}

/// All provider keys (the loader groups them by `provider_id`).
pub async fn list_provider_keys(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
) -> Result<Vec<ProviderKey>, sqlx::Error> {
    list_provider_keys_on(pool, kp).await
}

/// [`list_provider_keys`] on an arbitrary executor (one-transaction read).
pub(crate) async fn list_provider_keys_on<'e, E>(
    exec: E,
    kp: &dyn KeyProvider,
) -> Result<Vec<ProviderKey>, sqlx::Error>
where
    E: sqlx::Executor<'e, Database = sqlx::Sqlite>,
{
    let rows = sqlx::query_as!(
        ProviderKeyRow,
        r#"SELECT id as "id!", provider_id, created_at, api_key_ciphertext, api_key_nonce,
                  key_version
           FROM provider_key ORDER BY provider_id, created_at, id"#
    )
    .fetch_all(exec)
    .await?;
    rows.iter()
        .map(|r| r.to_model(kp).map_err(crypto_to_sqlx))
        .collect()
}

/// Keys belonging to a single provider (ordered by creation).
pub async fn list_provider_keys_by_provider(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    provider_id: &str,
) -> Result<Vec<ProviderKey>, sqlx::Error> {
    let rows = sqlx::query_as!(
        ProviderKeyRow,
        r#"SELECT id as "id!", provider_id, created_at, api_key_ciphertext, api_key_nonce,
                  key_version
           FROM provider_key WHERE provider_id = ? ORDER BY created_at"#,
        provider_id,
    )
    .fetch_all(pool)
    .await?;
    rows.iter()
        .map(|r| r.to_model(kp).map_err(crypto_to_sqlx))
        .collect()
}

pub async fn delete_provider_key(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM provider_key WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — Tenant
// ---------------------------------------------------------------------------

/// Insert a tenant. `auth_url` is NOT NULL → inserting with an empty/non-null
/// value is fine; a NULL would error at the SQLite layer.
///
/// Empty/blank `cert_file`/`cert_key` strings are normalized to `NULL`:
/// optional legacy cert paths arrive as `""` from the admin UI (and other
/// clients) when left blank, and an empty string is not a path — persisting
/// it would poison `build_config`/TLS resolution and the legacy cert
/// conversion (see `apply_tenant_cert`).
pub async fn insert_tenant(pool: &SqlitePool, t: &Tenant) -> Result<(), sqlx::Error> {
    let cert_key = non_empty_path(t.cert_key.as_deref());
    let cert_file = non_empty_path(t.cert_file.as_deref());
    sqlx::query!(
        "INSERT INTO tenant (id, name, domain, auth_url, cert_key, cert_file, enabled, \
         created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
        t.id,
        t.name,
        t.domain,
        t.auth_url,
        cert_key,
        cert_file,
        t.enabled,
        t.created_at,
        t.updated_at,
    )
    .execute(pool)
    .await?;
    Ok(())
}

/// Blank certificate paths are stored as `NULL` (empty string is not a path).
fn non_empty_path(p: Option<&str>) -> Option<String> {
    p.map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_string)
}

pub async fn get_tenant(pool: &SqlitePool, id: &str) -> Result<Tenant, sqlx::Error> {
    let row = sqlx::query_as!(
        TenantRow,
        r#"SELECT id as "id!", name, domain, auth_url, cert_key, cert_file, enabled,
                  created_at, updated_at
           FROM tenant WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_tenants(pool: &SqlitePool) -> Result<Vec<Tenant>, sqlx::Error> {
    let rows = sqlx::query_as!(
        TenantRow,
        r#"SELECT id as "id!", name, domain, auth_url, cert_key, cert_file, enabled,
                  created_at, updated_at
           FROM tenant ORDER BY created_at"#
    )
    .fetch_all(pool)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

/// Update a tenant's mutable fields (`name`, `domain`, `auth_url`, cert paths,
/// `enabled`, `updated_at`). Blank cert paths are normalized to `NULL`
/// (same rule as `insert_tenant`).
pub async fn update_tenant(pool: &SqlitePool, t: &Tenant) -> Result<(), sqlx::Error> {
    let cert_key = non_empty_path(t.cert_key.as_deref());
    let cert_file = non_empty_path(t.cert_file.as_deref());
    sqlx::query!(
        "UPDATE tenant SET name = ?, domain = ?, auth_url = ?, cert_key = ?, cert_file = ?, \
         enabled = ?, updated_at = ? WHERE id = ?",
        t.name,
        t.domain,
        t.auth_url,
        cert_key,
        cert_file,
        t.enabled,
        t.updated_at,
        t.id,
    )
    .execute(pool)
    .await?;
    Ok(())
}

/// Everything a tenant write must persist, in ONE transaction.
pub struct TenantWrite<'a> {
    pub tenant: &'a Tenant,
    /// `true` = INSERT (create), `false` = UPDATE (edit).
    pub is_create: bool,
    /// `Some(None)` = clear the token; `Some(Some(hash))` = set/rotate it;
    /// `None` = leave it alone.
    pub token_hash: Option<Option<String>>,
    /// `Some((None, None))` = clear the certificate; `Some((Some(pem), Some(key)))`
    /// = replace it; `None` = leave it alone.
    pub cert: Option<(Option<String>, Option<String>)>,
}

/// Upsert a tenant TOGETHER WITH its secret material, atomically.
///
/// Everything commits at once or not at all. Splitting these steps is the
/// "reported as failed but actually live" defect: the tenant row committed, then
/// the certificate or token write failed, and the API answered 500/400 while the
/// change was already in effect — the operator's natural retry then hits a
/// duplicate or re-applies a credential they were told had failed.
///
/// The post-write `reload` is deliberately NOT part of the transaction: it is
/// recoverable (the next successful reload fixes it) and is reported separately
/// through the response's `snapshot_stale` flag.
///
/// The SQL statements and their parameter types are byte-identical to the
/// single-purpose helpers they replace, so the committed `.sqlx` cache stays
/// valid for offline builds.
pub async fn write_tenant(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    w: TenantWrite<'_>,
) -> Result<(), sqlx::Error> {
    let t = w.tenant;
    let cert_key = non_empty_path(t.cert_key.as_deref());
    let cert_file = non_empty_path(t.cert_file.as_deref());
    let mut tx = begin_write(pool).await?;

    if w.is_create {
        sqlx::query!(
            "INSERT INTO tenant (id, name, domain, auth_url, cert_key, cert_file, enabled, \
             created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
            t.id,
            t.name,
            t.domain,
            t.auth_url,
            cert_key,
            cert_file,
            t.enabled,
            t.created_at,
            t.updated_at,
        )
        .execute(&mut *tx)
        .await?;
    } else {
        sqlx::query!(
            "UPDATE tenant SET name = ?, domain = ?, auth_url = ?, cert_key = ?, cert_file = ?, \
             enabled = ?, updated_at = ? WHERE id = ?",
            t.name,
            t.domain,
            t.auth_url,
            cert_key,
            cert_file,
            t.enabled,
            t.updated_at,
            t.id,
        )
        .execute(&mut *tx)
        .await?;
    }

    if let Some(hash) = &w.token_hash {
        // Bind first: `hash.as_deref()` would create a temporary that the query
        // borrows past the end of the statement.
        let hash: Option<&str> = hash.as_deref();
        sqlx::query!(
            "UPDATE tenant SET access_token_hash = ? WHERE id = ?",
            hash,
            t.id
        )
        .execute(&mut *tx)
        .await?;
    }

    if let Some((cert_pem, cert_key_pem)) = &w.cert {
        let (ct, nonce, version) = match cert_key_pem {
            Some(pem) => {
                let sealed = kp.seal(pem.as_bytes()).map_err(crypto_to_sqlx)?;
                (
                    Some(sealed.ciphertext),
                    Some(sealed.nonce.to_vec()),
                    Some(sealed.key_version as i64),
                )
            }
            None => (None, None, None),
        };
        sqlx::query!(
            "UPDATE tenant SET cert_pem = ?, cert_key_ciphertext = ?, cert_key_nonce = ?, \
             cert_key_version = ? WHERE id = ?",
            cert_pem,
            ct,
            nonce,
            version,
            t.id,
        )
        .execute(&mut *tx)
        .await?;
    }

    tx.commit().await?;
    Ok(())
}

pub async fn delete_tenant(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM tenant WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Tenant certificate content (migration 0007, cluster P0a)
// ---------------------------------------------------------------------------
//
// The cert is the tenant row itself: `cert_pem` (public, plaintext) +
// `cert_key_*` (AES-256-GCM sealed with the same master key as provider
// api-keys). The in-memory [`TenantCert`] carries the private key as
// plaintext only — it is decrypted at the DB boundary and never persisted or
// serialised.

/// Certificate content for one tenant, plaintext in memory.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TenantCert {
    pub tenant_id: String,
    /// Public cert PEM (`None` = no cert configured).
    pub cert_pem: Option<String>,
    /// Private key PEM, plaintext in memory only.
    pub cert_key_pem: Option<String>,
}

#[derive(sqlx::FromRow, Debug, Clone)]
struct TenantCertRow {
    tenant_id: String,
    cert_pem: Option<String>,
    cert_key_ciphertext: Option<Vec<u8>>,
    cert_key_nonce: Option<Vec<u8>>,
    cert_key_version: Option<i64>,
}

impl TenantCertRow {
    /// Decrypt the sealed private key into a plaintext [`TenantCert`]. A row
    /// with ciphertext but a bad/missing nonce or version is a hard decode
    /// error (tampered / wrong master key — fail-closed, like provider keys).
    fn to_model(&self, kp: &dyn KeyProvider) -> Result<TenantCert, sqlx::Error> {
        let cert_key_pem = match (
            &self.cert_key_ciphertext,
            &self.cert_key_nonce,
            self.cert_key_version,
        ) {
            (Some(ct), Some(nonce), Some(version)) => {
                let nonce: [u8; crypto::NONCE_LEN] = nonce
                    .as_slice()
                    .try_into()
                    .map_err(|_| crypto_to_sqlx(CryptoError::Decrypt))?;
                let sealed = Sealed {
                    ciphertext: ct.clone(),
                    nonce,
                    key_version: version as u32,
                };
                let plaintext = kp.open(&sealed).map_err(crypto_to_sqlx)?;
                Some(
                    String::from_utf8(plaintext)
                        .map_err(|_| crypto_to_sqlx(CryptoError::NotUtf8))?,
                )
            }
            _ => None,
        };
        Ok(TenantCert {
            tenant_id: self.tenant_id.clone(),
            cert_pem: self.cert_pem.clone(),
            cert_key_pem,
        })
    }
}

/// Fetch one tenant's certificate content (`None` when the tenant is absent).
pub async fn get_tenant_cert(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    tenant_id: &str,
) -> Result<Option<TenantCert>, sqlx::Error> {
    let row = sqlx::query_as!(
        TenantCertRow,
        r#"SELECT id as "tenant_id!", cert_pem, cert_key_ciphertext, cert_key_nonce,
                  cert_key_version
           FROM tenant WHERE id = ?"#,
        tenant_id
    )
    .fetch_optional(pool)
    .await?;
    row.map(|r| r.to_model(kp)).transpose()
}

/// All tenants' certificate content (the loader overlays this onto the
/// path-based `certs` map, content-first).
pub async fn list_tenant_certs(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
) -> Result<Vec<TenantCert>, sqlx::Error> {
    let rows = sqlx::query_as!(
        TenantCertRow,
        r#"SELECT id as "tenant_id!", cert_pem, cert_key_ciphertext, cert_key_nonce,
                  cert_key_version
           FROM tenant ORDER BY id"#
    )
    .fetch_all(pool)
    .await?;
    rows.iter().map(|r| r.to_model(kp)).collect()
}

/// Write a tenant's certificate content. `None` fields clear the columns
/// (explicit cert removal). The private key is sealed at the DB boundary —
/// the caller passes plaintext, this function persists ciphertext only.
pub async fn update_tenant_cert(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    cert: &TenantCert,
) -> Result<(), sqlx::Error> {
    let (ct, nonce, version) = match &cert.cert_key_pem {
        Some(pem) => {
            let sealed = kp.seal(pem.as_bytes()).map_err(crypto_to_sqlx)?;
            (
                Some(sealed.ciphertext),
                Some(sealed.nonce.to_vec()),
                Some(sealed.key_version as i64),
            )
        }
        None => (None, None, None),
    };
    sqlx::query!(
        "UPDATE tenant SET cert_pem = ?, cert_key_ciphertext = ?, cert_key_nonce = ?, \
         cert_key_version = ? WHERE id = ?",
        cert.cert_pem,
        ct,
        nonce,
        version,
        cert.tenant_id,
    )
    .execute(pool)
    .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Tenant access token (migration 0009, self-service auth-cache invalidation)
// ---------------------------------------------------------------------------
//
// The tenant self-service credential is stored as a SHA-256 hex HASH only —
// one-way, never echoed, never recoverable (lost token => rotate via the
// admin API / UI). It is compared, never used for outbound calls, so a hash
// is the correct primitive (same reasoning as the AuthCache's api-key
// digests).

/// Set (or clear, `None`) a tenant's access-token hash.
pub async fn set_tenant_access_token_hash(
    pool: &SqlitePool,
    tenant_id: &str,
    hash: Option<&str>,
) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "UPDATE tenant SET access_token_hash = ? WHERE id = ?",
        hash,
        tenant_id
    )
    .execute(pool)
    .await?;
    Ok(())
}

/// All `(tenant_id, access_token_hash)` pairs — the tenant-token gate scans
/// these and compares the presented token's digest (constant-time).
pub async fn list_tenant_access_token_hashes(
    pool: &SqlitePool,
) -> Result<Vec<(String, String)>, sqlx::Error> {
    list_tenant_access_token_hashes_on(pool).await
}

/// [`list_tenant_access_token_hashes`] on an arbitrary executor
/// (one-transaction read).
pub(crate) async fn list_tenant_access_token_hashes_on<'e, E>(
    exec: E,
) -> Result<Vec<(String, String)>, sqlx::Error>
where
    E: sqlx::Executor<'e, Database = sqlx::Sqlite>,
{
    let rows = sqlx::query!(
        "SELECT id, access_token_hash FROM tenant WHERE access_token_hash IS NOT NULL \
           ORDER BY id"
    )
    .fetch_all(exec)
    .await?;
    Ok(rows
        .into_iter()
        // `id` is `TEXT PRIMARY KEY` without NOT NULL, so sqlx types it
        // Option<String> — a PK can never be NULL, unwrap_or_default is safe.
        .filter_map(|r| r.access_token_hash.map(|h| (r.id.unwrap_or_default(), h)))
        .collect())
}

/// Whether a tenant has an access token configured (for the admin view).
pub async fn tenant_has_access_token(
    pool: &SqlitePool,
    tenant_id: &str,
) -> Result<bool, sqlx::Error> {
    let row = sqlx::query!(
        "SELECT access_token_hash FROM tenant WHERE id = ?",
        tenant_id
    )
    .fetch_optional(pool)
    .await?;
    Ok(row.and_then(|r| r.access_token_hash).is_some())
}

/// One-time backfill for migration 0007: tenants with legacy `cert_file` /
/// `cert_key` paths but no stored content get their files read on this node
/// and stored as content (so the DB becomes self-contained and the shared
/// cert volume can be dropped). Best-effort: a failure is logged per tenant
/// and never aborts startup — the path fallback keeps serving until the files
/// become readable or the operator re-enters the cert via the admin API.
pub async fn backfill_legacy_certs(pool: &SqlitePool, kp: &dyn KeyProvider) {
    let tenants = match list_tenants(pool).await {
        Ok(t) => t,
        Err(e) => {
            tracing::warn!(error = %e, "cert backfill: list_tenants failed; skipping");
            return;
        }
    };
    let existing = match list_tenant_certs(pool, kp).await {
        Ok(c) => c,
        Err(e) => {
            tracing::warn!(error = %e, "cert backfill: list_tenant_certs failed; skipping");
            return;
        }
    };
    let with_content: std::collections::HashSet<&str> = existing
        .iter()
        .filter(|c| c.cert_pem.is_some())
        .map(|c| c.tenant_id.as_str())
        .collect();

    for t in tenants {
        if with_content.contains(t.id.as_str()) {
            continue;
        }
        let (Some(cert_path), Some(key_path)) = (&t.cert_file, &t.cert_key) else {
            continue;
        };
        let (Ok(cert_bytes), Ok(key_bytes)) = (std::fs::read(cert_path), std::fs::read(key_path))
        else {
            tracing::warn!(
                tenant = %t.id,
                cert_path,
                key_path,
                "cert backfill: legacy cert paths not readable on this node; path fallback remains active"
            );
            continue;
        };
        let cert = TenantCert {
            tenant_id: t.id.clone(),
            cert_pem: Some(String::from_utf8_lossy(&cert_bytes).into_owned()),
            cert_key_pem: Some(String::from_utf8_lossy(&key_bytes).into_owned()),
        };
        match update_tenant_cert(pool, kp, &cert).await {
            Ok(()) => tracing::info!(tenant = %t.id, "cert backfill: legacy paths -> content"),
            Err(e) => tracing::warn!(tenant = %t.id, error = %e, "cert backfill: store failed"),
        }
    }
}

// ---------------------------------------------------------------------------
// CRUD — TenantProvider
// ---------------------------------------------------------------------------

pub async fn insert_tenant_provider(
    pool: &SqlitePool,
    tp: &TenantProvider,
) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "INSERT INTO tenant_provider (id, tenant_id, provider_id) VALUES (?, ?, ?)",
        tp.id,
        tp.tenant_id,
        tp.provider_id,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_tenant_provider(
    pool: &SqlitePool,
    id: &str,
) -> Result<TenantProvider, sqlx::Error> {
    let row = sqlx::query_as!(
        TenantProviderRow,
        r#"SELECT id as "id!", tenant_id, provider_id
           FROM tenant_provider WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_tenant_providers(pool: &SqlitePool) -> Result<Vec<TenantProvider>, sqlx::Error> {
    list_tenant_providers_on(pool).await
}

/// [`list_tenant_providers`] on an arbitrary executor (one-transaction read).
pub(crate) async fn list_tenant_providers_on<'e, E>(
    exec: E,
) -> Result<Vec<TenantProvider>, sqlx::Error>
where
    E: sqlx::Executor<'e, Database = sqlx::Sqlite>,
{
    let rows = sqlx::query_as!(
        TenantProviderRow,
        r#"SELECT id as "id!", tenant_id, provider_id
           FROM tenant_provider ORDER BY tenant_id, provider_id"#
    )
    .fetch_all(exec)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

pub async fn delete_tenant_provider(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM tenant_provider WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — TenantModel
// ---------------------------------------------------------------------------

pub async fn insert_tenant_model(pool: &SqlitePool, tm: &TenantModel) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "INSERT INTO tenant_model (id, tenant_id, model_key) VALUES (?, ?, ?)",
        tm.id,
        tm.tenant_id,
        tm.model_key,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_tenant_model(pool: &SqlitePool, id: &str) -> Result<TenantModel, sqlx::Error> {
    let row = sqlx::query_as!(
        TenantModelRow,
        r#"SELECT id as "id!", tenant_id, model_key
           FROM tenant_model WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_tenant_models(pool: &SqlitePool) -> Result<Vec<TenantModel>, sqlx::Error> {
    list_tenant_models_on(pool).await
}

/// [`list_tenant_models`] on an arbitrary executor (one-transaction read).
pub(crate) async fn list_tenant_models_on<'e, E>(exec: E) -> Result<Vec<TenantModel>, sqlx::Error>
where
    E: sqlx::Executor<'e, Database = sqlx::Sqlite>,
{
    let rows = sqlx::query_as!(
        TenantModelRow,
        r#"SELECT id as "id!", tenant_id, model_key
           FROM tenant_model ORDER BY tenant_id, model_key"#
    )
    .fetch_all(exec)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

pub async fn delete_tenant_model(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM tenant_model WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — LimitRole
// ---------------------------------------------------------------------------
//
// `matching_key` holds a CLIENT CREDENTIAL, and it is sealed at this boundary (decision D-16,
// 2026-10-08 — the user's ruling: seal the column, and re-seal legacy rows without a manual step).
// The three functions below split that one policy three ways:
//
//   * write (`insert_limit_role` / `update_limit_role`): `kp.seal(..).to_text()`. This column never
//     receives a client key again.
//   * read (`get_limit_role` / `list_limit_roles[_on]`): `crypto::Sealed::open_text`, which opens an
//     envelope and passes a NON-envelope value through as plaintext. The migration below runs before
//     the LOADER's own read, so what that branch actually serves is every OTHER reader — chiefly an
//     admin `GET` before the migration has run. (Measured while falsifying this: see
//     `crypto::Sealed::open_text`, which carries the probe's result.) The config TREE gets no such
//     fallback on purpose; it is versioned by `TOC_FORMAT`, which D-16 bumped.
//   * [`seal_legacy_limit_keys`]: the ONE place that rewrites a legacy row, called by the config
//     loader. That is what makes the migration automatic; a reader never writes.

/// The at-rest form of a `limit_role.matching_key` value: sealed, or `None` for SQL NULL.
fn seal_limit_key(kp: &dyn KeyProvider, key: Option<&str>) -> Result<Option<String>, sqlx::Error> {
    match key {
        None => Ok(None),
        Some(k) => Ok(Some(
            kp.seal(k.as_bytes()).map_err(crypto_to_sqlx)?.to_text(),
        )),
    }
}

/// The in-memory form of a stored `limit_role.matching_key` value.
///
/// The whole policy lives in [`crate::crypto::Sealed::open_text`] and is NOT re-derived here: the
/// config tree carries the same values in the same text form, and two copies of "is this sealed?"
/// is how the two would drift apart.
fn open_limit_key(
    kp: &dyn KeyProvider,
    stored: Option<String>,
) -> Result<Option<String>, sqlx::Error> {
    match stored {
        None => Ok(None),
        Some(value) => Sealed::open_text(kp, &value)
            .map(Some)
            .map_err(crypto_to_sqlx),
    }
}

pub async fn insert_limit_role(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    r: &LimitRole,
) -> Result<(), sqlx::Error> {
    let matching_key = seal_limit_key(kp, r.matching_key.as_deref())?;
    sqlx::query!(
        "INSERT INTO limit_role (id, name, matching_key, matching_model, matching_tenant, \
         matching_provider, limit_count, limit_token, window, enabled, created_at) \
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        r.id,
        r.name,
        matching_key,
        r.matching_model,
        r.matching_tenant,
        r.matching_provider,
        r.limit_count,
        r.limit_token,
        r.window,
        r.enabled,
        r.created_at,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_limit_role(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    id: &str,
) -> Result<LimitRole, sqlx::Error> {
    let row = sqlx::query_as!(
        LimitRoleRow,
        r#"SELECT id as "id!", name, matching_key, matching_model, matching_tenant,
                  matching_provider, limit_count, limit_token, window, enabled, created_at
           FROM limit_role WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    row.to_model(kp)
}

pub async fn list_limit_roles(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
) -> Result<Vec<LimitRole>, sqlx::Error> {
    list_limit_roles_on(pool, kp).await
}

/// [`list_limit_roles`] on an arbitrary executor, so the replication content can
/// read it inside ONE transaction (see `cluster::content::ReplicationContent::load`).
///
/// NOTE for that caller: this function only READS. The legacy re-seal is
/// [`seal_legacy_limit_keys`], which opens its own write transaction, precisely because this one is
/// called inside a plain (deferred) read transaction — a write here would have to take the write
/// lock mid-read and would fail a node whose only sin was reading while an admin write was in
/// flight.
pub(crate) async fn list_limit_roles_on<'e, E>(
    exec: E,
    kp: &dyn KeyProvider,
) -> Result<Vec<LimitRole>, sqlx::Error>
where
    E: sqlx::Executor<'e, Database = sqlx::Sqlite>,
{
    let rows = sqlx::query_as!(
        LimitRoleRow,
        r#"SELECT id as "id!", name, matching_key, matching_model, matching_tenant,
                  matching_provider, limit_count, limit_token, window, enabled, created_at
           FROM limit_role ORDER BY created_at, id"#
    )
    .fetch_all(exec)
    .await?;
    rows.iter().map(|r| r.to_model(kp)).collect()
}

/// The rows that still hold a PLAINTEXT `matching_key` — exactly what [`seal_legacy_limit_keys`] will
/// rewrite.
///
/// Split out from the migration on purpose: the migration's READ is one plain statement on the pool
/// and its WRITE is a compare-and-swap inside a write transaction, and the property that matters
/// (a row that changed in between is not clobbered) only exists in the gap between them. A test that
/// wants to model that gap has to be able to hold the two halves apart — otherwise it ends up
/// asserting a COPY of the UPDATE text, which stays green after the production clause is deleted.
async fn legacy_limit_key_rows(pool: &SqlitePool) -> Result<Vec<(String, String)>, sqlx::Error> {
    let rows: Vec<(String, String)> = sqlx::query_as(
        "SELECT id, matching_key FROM limit_role WHERE matching_key IS NOT NULL ORDER BY id",
    )
    .fetch_all(pool)
    .await?;
    Ok(rows
        .into_iter()
        .filter(|(_, value)| Sealed::from_text(value).is_none())
        .collect())
}

/// Seal ONE legacy row: `stale` is the plaintext the reader saw, `fresh` its envelope. Returns the
/// number of rows actually rewritten (0 or 1) — 0 when the row changed, was deleted, or was sealed by
/// another node in the meantime, none of which is an error.
async fn reseal_limit_key_row<'e, E>(
    exec: E,
    id: &str,
    stale: &str,
    fresh: &str,
) -> Result<u64, sqlx::Error>
where
    E: sqlx::Executor<'e, Database = sqlx::Sqlite>,
{
    let done =
        sqlx::query("UPDATE limit_role SET matching_key = ? WHERE id = ? AND matching_key = ?")
            .bind(fresh)
            .bind(id)
            .bind(stale)
            .execute(exec)
            .await?;
    Ok(done.rows_affected())
}

/// Seal every `limit_role.matching_key` still stored as PLAINTEXT. Returns how many rows were
/// rewritten (0 on a database that is already sealed).
///
/// ## Why this exists, and why it is not inside the reader
///
/// Decision D-16 says an upgrade needs no manual step. The rows written before that decision hold a
/// client key in the clear, so something has to rewrite them — and that something must be a WRITE,
/// with its own transaction, not a side effect of a read (see [`list_limit_roles_on`]).
///
/// ## Shape
///
/// 1. [`legacy_limit_key_rows`] reads first, with no lock: on a sealed database this function opens
///    no write transaction at all, which is what keeps "the loader ran" from meaning "the loader took
///    the write lock" on every reload.
/// 2. Each write is [`reseal_limit_key_row`]'s compare-and-swap, so an admin write (or another node)
///    landing between the read and the write wins and this pass affects nothing.
/// 3. Only rows that actually changed are counted, so the caller's log line means what it says.
///
/// # Errors
/// A [`CryptoError`] from sealing, or a SQL error from the update.
pub async fn seal_legacy_limit_keys(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
) -> Result<usize, sqlx::Error> {
    let pending = legacy_limit_key_rows(pool).await?;
    if pending.is_empty() {
        return Ok(0); // already sealed: not even a write transaction is opened
    }

    let mut tx = begin_write(pool).await?;
    let mut resealed = 0usize;
    for (id, value) in pending {
        let fresh = kp.seal(value.as_bytes()).map_err(crypto_to_sqlx)?.to_text();
        resealed += reseal_limit_key_row(&mut *tx, &id, &value, &fresh).await? as usize;
    }
    tx.commit().await?;
    Ok(resealed)
}

/// Update a limit role's mutable fields.
pub async fn update_limit_role(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
    r: &LimitRole,
) -> Result<(), sqlx::Error> {
    let matching_key = seal_limit_key(kp, r.matching_key.as_deref())?;
    sqlx::query!(
        "UPDATE limit_role SET name = ?, matching_key = ?, matching_model = ?, \
         matching_tenant = ?, matching_provider = ?, limit_count = ?, limit_token = ?, \
         window = ?, enabled = ? WHERE id = ?",
        r.name,
        matching_key,
        r.matching_model,
        r.matching_tenant,
        r.matching_provider,
        r.limit_count,
        r.limit_token,
        r.window,
        r.enabled,
        r.id,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn delete_limit_role(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM limit_role WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — provider_key_binding (design §7.1b)
// ---------------------------------------------------------------------------

/// Insert a binding. Violating the UNIQUE `key_prefix` constraint returns a
/// sqlx UNIQUE violation (→ 409 by the admin layer).
pub async fn insert_provider_key_binding(
    pool: &SqlitePool,
    b: &ProviderKeyBinding,
) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "INSERT INTO provider_key_binding (id, key_prefix, provider_id, enabled, created_at, \
         updated_at) VALUES (?, ?, ?, ?, ?, ?)",
        b.id,
        b.key_prefix,
        b.provider_id,
        b.enabled,
        b.created_at,
        b.updated_at
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_provider_key_binding(
    pool: &SqlitePool,
    id: &str,
) -> Result<ProviderKeyBinding, sqlx::Error> {
    let row = sqlx::query_as!(
        ProviderKeyBindingRow,
        r#"SELECT id as "id!", key_prefix, provider_id, enabled, created_at, updated_at
           FROM provider_key_binding WHERE id = ?"#,
        id
    )
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_provider_key_bindings(
    pool: &SqlitePool,
) -> Result<Vec<ProviderKeyBinding>, sqlx::Error> {
    list_provider_key_bindings_on(pool).await
}

/// [`list_provider_key_bindings`] on an arbitrary executor (one-transaction read).
pub(crate) async fn list_provider_key_bindings_on<'e, E>(
    exec: E,
) -> Result<Vec<ProviderKeyBinding>, sqlx::Error>
where
    E: sqlx::Executor<'e, Database = sqlx::Sqlite>,
{
    let rows = sqlx::query_as!(
        ProviderKeyBindingRow,
        r#"SELECT id as "id!", key_prefix, provider_id, enabled, created_at, updated_at
           FROM provider_key_binding ORDER BY key_prefix"#
    )
    .fetch_all(exec)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

/// Update a binding's mutable fields (prefix / provider / enabled).
pub async fn update_provider_key_binding(
    pool: &SqlitePool,
    b: &ProviderKeyBinding,
) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "UPDATE provider_key_binding SET key_prefix = ?, provider_id = ?, enabled = ?, \
         updated_at = ? WHERE id = ?",
        b.key_prefix,
        b.provider_id,
        b.enabled,
        b.updated_at,
        b.id
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn delete_provider_key_binding(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    sqlx::query!("DELETE FROM provider_key_binding WHERE id = ?", id)
        .execute(pool)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// CRUD — sub_tenant / sub_tenant_route (design-sub-tenant.md §3.1)
//
// These use **runtime** `sqlx::query` / `query_as` (the `db/restore.rs` style)
// rather than the compile-time `query!`/`query_as!` macros used above, so no
// `.sqlx/` offline-cache refresh is required (T1 added no query macros).
// `enabled` maps `INTEGER`↔`bool` at the boundary (`i64` in the row, `!= 0`
// → `bool`); `model_key` maps `NULL`↔`Option<String>`; `updated_at` is set
// server-side to `datetime('now')` on update.
// ---------------------------------------------------------------------------

/// Insert a sub-tenant. Violating `UNIQUE(tenant_id, name)` or
/// `UNIQUE(tenant_id, key_prefix)` returns a sqlx UNIQUE violation (→ 409 by
/// the admin layer).
pub async fn insert_sub_tenant(pool: &SqlitePool, st: &SubTenant) -> Result<(), sqlx::Error> {
    sqlx::query(
        "INSERT INTO sub_tenant (id, tenant_id, name, key_prefix, enabled, created_at, \
         updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
    )
    .bind(&st.id)
    .bind(&st.tenant_id)
    .bind(&st.name)
    .bind(&st.key_prefix)
    .bind(st.enabled)
    .bind(&st.created_at)
    .bind(&st.updated_at)
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_sub_tenant(pool: &SqlitePool, id: &str) -> Result<SubTenant, sqlx::Error> {
    let row: SubTenantRow = sqlx::query_as(
        "SELECT id, tenant_id, name, key_prefix, enabled, created_at, updated_at \
         FROM sub_tenant WHERE id = ?",
    )
    .bind(id)
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_sub_tenants(pool: &SqlitePool) -> Result<Vec<SubTenant>, sqlx::Error> {
    list_sub_tenants_on(pool).await
}

/// [`list_sub_tenants`] on an arbitrary executor (one-transaction read).
pub(crate) async fn list_sub_tenants_on<'e, E>(exec: E) -> Result<Vec<SubTenant>, sqlx::Error>
where
    E: sqlx::Executor<'e, Database = sqlx::Sqlite>,
{
    let rows: Vec<SubTenantRow> = sqlx::query_as(
        "SELECT id, tenant_id, name, key_prefix, enabled, created_at, updated_at \
         FROM sub_tenant ORDER BY tenant_id, name",
    )
    .fetch_all(exec)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

/// Update a sub-tenant's mutable fields (name / key_prefix / enabled).
/// `updated_at` is set server-side to `datetime('now')`.
pub async fn update_sub_tenant(pool: &SqlitePool, st: &SubTenant) -> Result<(), sqlx::Error> {
    update_sub_tenant_on(pool, st).await
}

/// [`update_sub_tenant`] on an arbitrary executor (one-transaction write).
pub(crate) async fn update_sub_tenant_on<'e, E>(exec: E, st: &SubTenant) -> Result<(), sqlx::Error>
where
    E: sqlx::Executor<'e, Database = sqlx::Sqlite>,
{
    sqlx::query(
        "UPDATE sub_tenant SET name = ?, key_prefix = ?, enabled = ?, \
         updated_at = datetime('now') WHERE id = ?",
    )
    .bind(&st.name)
    .bind(&st.key_prefix)
    .bind(st.enabled)
    .bind(&st.id)
    .execute(exec)
    .await?;
    Ok(())
}

pub async fn delete_sub_tenant(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    delete_sub_tenant_on(pool, id).await
}

/// [`delete_sub_tenant`] on an arbitrary executor (one-transaction write).
pub(crate) async fn delete_sub_tenant_on<'e, E>(exec: E, id: &str) -> Result<(), sqlx::Error>
where
    E: sqlx::Executor<'e, Database = sqlx::Sqlite>,
{
    sqlx::query("DELETE FROM sub_tenant WHERE id = ?")
        .bind(id)
        .execute(exec)
        .await?;
    Ok(())
}

/// Insert a sub-tenant route. Violating the model-specific or default-route
/// partial unique index returns a sqlx UNIQUE violation (→ 409 by the admin
/// layer).
pub async fn insert_sub_tenant_route(
    pool: &SqlitePool,
    r: &SubTenantRoute,
) -> Result<(), sqlx::Error> {
    sqlx::query(
        "INSERT INTO sub_tenant_route (id, sub_tenant_id, model_key, provider_id, enabled, \
         created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
    )
    .bind(&r.id)
    .bind(&r.sub_tenant_id)
    .bind(&r.model_key)
    .bind(&r.provider_id)
    .bind(r.enabled)
    .bind(&r.created_at)
    .bind(&r.updated_at)
    .execute(pool)
    .await?;
    Ok(())
}

pub async fn get_sub_tenant_route(
    pool: &SqlitePool,
    id: &str,
) -> Result<SubTenantRoute, sqlx::Error> {
    let row: SubTenantRouteRow = sqlx::query_as(
        "SELECT id, sub_tenant_id, model_key, provider_id, enabled, created_at, updated_at \
         FROM sub_tenant_route WHERE id = ?",
    )
    .bind(id)
    .fetch_one(pool)
    .await?;
    Ok(row.into())
}

pub async fn list_sub_tenant_routes(pool: &SqlitePool) -> Result<Vec<SubTenantRoute>, sqlx::Error> {
    list_sub_tenant_routes_on(pool).await
}

/// [`list_sub_tenant_routes`] on an arbitrary executor (one-transaction read).
pub(crate) async fn list_sub_tenant_routes_on<'e, E>(
    exec: E,
) -> Result<Vec<SubTenantRoute>, sqlx::Error>
where
    E: sqlx::Executor<'e, Database = sqlx::Sqlite>,
{
    let rows: Vec<SubTenantRouteRow> = sqlx::query_as(
        "SELECT id, sub_tenant_id, model_key, provider_id, enabled, created_at, updated_at \
         FROM sub_tenant_route ORDER BY sub_tenant_id, model_key",
    )
    .fetch_all(exec)
    .await?;
    Ok(rows.into_iter().map(Into::into).collect())
}

/// Update a route's mutable fields (model_key / provider_id / enabled).
/// `updated_at` is set server-side to `datetime('now')`.
pub async fn update_sub_tenant_route(
    pool: &SqlitePool,
    r: &SubTenantRoute,
) -> Result<(), sqlx::Error> {
    update_sub_tenant_route_on(pool, r).await
}

/// [`update_sub_tenant_route`] on an arbitrary executor (one-transaction
/// write).
pub(crate) async fn update_sub_tenant_route_on<'e, E>(
    exec: E,
    r: &SubTenantRoute,
) -> Result<(), sqlx::Error>
where
    E: sqlx::Executor<'e, Database = sqlx::Sqlite>,
{
    sqlx::query(
        "UPDATE sub_tenant_route SET model_key = ?, provider_id = ?, enabled = ?, \
         updated_at = datetime('now') WHERE id = ?",
    )
    .bind(&r.model_key)
    .bind(&r.provider_id)
    .bind(r.enabled)
    .bind(&r.id)
    .execute(exec)
    .await?;
    Ok(())
}

pub async fn delete_sub_tenant_route(pool: &SqlitePool, id: &str) -> Result<(), sqlx::Error> {
    delete_sub_tenant_route_on(pool, id).await
}

/// [`delete_sub_tenant_route`] on an arbitrary executor (one-transaction
/// write).
pub(crate) async fn delete_sub_tenant_route_on<'e, E>(exec: E, id: &str) -> Result<(), sqlx::Error>
where
    E: sqlx::Executor<'e, Database = sqlx::Sqlite>,
{
    sqlx::query("DELETE FROM sub_tenant_route WHERE id = ?")
        .bind(id)
        .execute(exec)
        .await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Sub-tenant / route write helpers (sub-tenant v2, D4/D5)
//
// Executor-generic so the transactional write core can call them inside a
// `begin_write` transaction (passing `&mut *tx`) — see [`begin_write`] for why
// every transaction in this crate is `BEGIN IMMEDIATE`. All use **runtime**
// `sqlx::query` / `query_as` (no `.sqlx/` refresh).
// ---------------------------------------------------------------------------

/// Count ALL sub-tenants for a tenant (ignoring `enabled`), on an executor
/// (e.g. `&mut *tx` inside the write transaction). Supports the all-rows quota
/// (A-2 finding 1) without loading every row.
pub async fn count_sub_tenants_by_tenant_on<'e, E>(
    exec: E,
    tenant_id: &str,
) -> Result<i64, sqlx::Error>
where
    E: sqlx::Executor<'e, Database = sqlx::Sqlite>,
{
    let (count,): (i64,) = sqlx::query_as("SELECT COUNT(*) FROM sub_tenant WHERE tenant_id = ?")
        .bind(tenant_id)
        .fetch_one(exec)
        .await?;
    Ok(count)
}

/// Count ALL routes for a sub-tenant (ignoring `enabled`), on an executor.
pub async fn count_sub_tenant_routes_by_sub_tenant_on<'e, E>(
    exec: E,
    sub_tenant_id: &str,
) -> Result<i64, sqlx::Error>
where
    E: sqlx::Executor<'e, Database = sqlx::Sqlite>,
{
    let (count,): (i64,) =
        sqlx::query_as("SELECT COUNT(*) FROM sub_tenant_route WHERE sub_tenant_id = ?")
            .bind(sub_tenant_id)
            .fetch_one(exec)
            .await?;
    Ok(count)
}

/// Upsert a sub-tenant keyed on its natural key `UNIQUE(tenant_id, name)`.
///
/// On a `(tenant_id, name)` conflict the row's `key_prefix` / `enabled` /
/// `updated_at` are updated and the EXISTING `id` is kept (idempotent `PUT` by
/// name, A-2 prerequisite 4). A `key_prefix` that collides with a DIFFERENT
/// row's prefix (the separate `UNIQUE(tenant_id, key_prefix)` constraint) is
/// NOT swallowed: the `ON CONFLICT (tenant_id, name)` target only resolves the
/// name conflict, so the key-prefix violation surfaces as a sqlx UNIQUE
/// violation for the caller to map to 409.
///
/// `id` is the row id to use when a NEW row is inserted; on conflict the
/// existing id is retained.
///
/// Takes the transaction's **connection** (`&mut *tx`, where `tx` is the owned
/// `sqlx::Transaction`) so the statements run inside the caller's transaction.
pub async fn upsert_sub_tenant_by_name(
    tx: &mut sqlx::sqlite::SqliteConnection,
    id: &str,
    tenant_id: &str,
    name: &str,
    key_prefix: &str,
    enabled: bool,
) -> Result<SubTenant, sqlx::Error> {
    sqlx::query(
        "INSERT INTO sub_tenant (id, tenant_id, name, key_prefix, enabled, created_at, \
         updated_at) VALUES (?, ?, ?, ?, ?, datetime('now'), datetime('now')) \
         ON CONFLICT (tenant_id, name) DO UPDATE SET \
             key_prefix = excluded.key_prefix, \
             enabled = excluded.enabled, \
             updated_at = datetime('now')",
    )
    .bind(id)
    .bind(tenant_id)
    .bind(name)
    .bind(key_prefix)
    .bind(enabled)
    .execute(&mut *tx)
    .await?;

    let row: SubTenantRow = sqlx::query_as(
        "SELECT id, tenant_id, name, key_prefix, enabled, created_at, updated_at \
         FROM sub_tenant WHERE tenant_id = ? AND name = ?",
    )
    .bind(tenant_id)
    .bind(name)
    .fetch_one(&mut *tx)
    .await?;
    Ok(row.into())
}

/// Upsert a sub-tenant route keyed on its natural key `(sub_tenant_id,
/// model_key)`, handling BOTH partial unique indexes:
/// - `model_key = Some(m)` → `ON CONFLICT (sub_tenant_id, model_key) WHERE
///   (model_key IS NOT NULL)` (the model-specific index);
/// - `model_key = None` → `ON CONFLICT (sub_tenant_id) WHERE (model_key IS
///   NULL)` (the default-route index).
///
/// On conflict the existing `id` is kept (idempotent `PUT` by key). `id` is the
/// row id to use when a NEW row is inserted.
///
/// Takes the transaction's **connection** (`&mut *tx`, where `tx` is the owned
/// `sqlx::Transaction`) so the statements run inside the caller's transaction.
pub async fn upsert_sub_tenant_route_by_key(
    tx: &mut sqlx::sqlite::SqliteConnection,
    id: &str,
    sub_tenant_id: &str,
    model_key: Option<&str>,
    provider_id: &str,
    enabled: bool,
) -> Result<SubTenantRoute, sqlx::Error> {
    match model_key {
        Some(model_key) => {
            sqlx::query(
                "INSERT INTO sub_tenant_route (id, sub_tenant_id, model_key, provider_id, \
                 enabled, created_at, updated_at) \
                 VALUES (?, ?, ?, ?, ?, datetime('now'), datetime('now')) \
                 ON CONFLICT (sub_tenant_id, model_key) WHERE (model_key IS NOT NULL) DO UPDATE SET \
                     provider_id = excluded.provider_id, \
                     enabled = excluded.enabled, \
                     updated_at = datetime('now')",
            )
            .bind(id)
            .bind(sub_tenant_id)
            .bind(model_key)
            .bind(provider_id)
            .bind(enabled)
            .execute(&mut *tx)
            .await?;
        }
        None => {
            sqlx::query(
                "INSERT INTO sub_tenant_route (id, sub_tenant_id, model_key, provider_id, \
                 enabled, created_at, updated_at) \
                 VALUES (?, ?, NULL, ?, ?, datetime('now'), datetime('now')) \
                 ON CONFLICT (sub_tenant_id) WHERE (model_key IS NULL) DO UPDATE SET \
                     provider_id = excluded.provider_id, \
                     enabled = excluded.enabled, \
                     updated_at = datetime('now')",
            )
            .bind(id)
            .bind(sub_tenant_id)
            .bind(provider_id)
            .bind(enabled)
            .execute(&mut *tx)
            .await?;
        }
    }

    let row: SubTenantRouteRow = match model_key {
        Some(model_key) => {
            sqlx::query_as(
                "SELECT id, sub_tenant_id, model_key, provider_id, enabled, created_at, \
                 updated_at FROM sub_tenant_route WHERE sub_tenant_id = ? AND model_key = ?",
            )
            .bind(sub_tenant_id)
            .bind(model_key)
            .fetch_one(&mut *tx)
            .await?
        }
        None => {
            sqlx::query_as(
                "SELECT id, sub_tenant_id, model_key, provider_id, enabled, created_at, \
                 updated_at FROM sub_tenant_route WHERE sub_tenant_id = ? AND model_key IS NULL",
            )
            .bind(sub_tenant_id)
            .fetch_one(&mut *tx)
            .await?
        }
    };
    Ok(row.into())
}

// ---------------------------------------------------------------------------
// Config version metadata + full-table config restore (cluster P1/P2)
// ---------------------------------------------------------------------------
//
// `config_meta` (migration 0008) holds control-plane bookkeeping; today the
// standby replica's last-applied `config_version`. `restore_config` rebuilds
// every config table from a snapshot in ONE transaction (standby replica
// materialization, cluster P2) so a crash mid-restore never leaves a
// half-config. It uses runtime-checked `sqlx::query` (like the sinks): the
// statements run against a live migration-pinned DB and the tables are tiny.

/// The stored last-applied config version, in three states — see
/// [`ConfigVersion`] (this replaced an `Option<u64>` that could not tell
/// "never set" from "corrupt").
///
/// `Absent` (no row) and `Corrupt` (a row whose value is not a number) are
/// different facts that call for different safe responses. Collapsing them —
/// which a bare `value.parse().ok()` did — turned a corrupted watermark into
/// "never set", and "never set" plus an empty replica evaluates to
/// `replica_is_current(.., 0) == true`: a node that cannot prove it holds the
/// current config could be judged fresh and win the leader lease.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ConfigVersion {
    /// No marker row at all: a brand-new DB, or one predating migration 0008.
    Absent,
    /// A parsed watermark.
    Value(u64),
    /// A row exists but its value is not a `u64` (hand edit, partial import,
    /// truncated restore). Carries the raw text so the warning can quote what an
    /// operator has to look at.
    Corrupt(String),
}

/// Read the config watermark ([`ConfigVersion`] — see why it is three-state).
pub async fn get_config_version(pool: &SqlitePool) -> Result<ConfigVersion, sqlx::Error> {
    let row: Option<(String,)> =
        sqlx::query_as("SELECT value FROM config_meta WHERE key = 'config_version'")
            .fetch_optional(pool)
            .await?;
    Ok(match row {
        None => ConfigVersion::Absent,
        // Surrounding whitespace is tolerated (a `sqlite3` hand-edit almost
        // always adds a newline); anything else unparseable is Corrupt.
        Some((v,)) => match v.trim().parse::<u64>() {
            Ok(n) => ConfigVersion::Value(n),
            Err(_) => ConfigVersion::Corrupt(v),
        },
    })
}

/// Whether the config tables hold ANY row.
///
/// Used only to tell two indistinguishable-by-version states apart at boot:
/// a brand-new DB (nothing configured yet ⇒ version 0, a node that holds
/// nothing and must sync before it may lead) versus a DB that predates
/// migration 0008 or was imported (content but no `config_version` marker ⇒
/// version 1, a cluster that really does have config). Table names are static
/// literals — nothing is interpolated at runtime.
pub async fn config_content_exists(pool: &SqlitePool) -> Result<bool, sqlx::Error> {
    let row: (i64,) = sqlx::query_as(
        "SELECT EXISTS(SELECT 1 FROM tenant LIMIT 1) \
           OR EXISTS(SELECT 1 FROM provider LIMIT 1) \
           OR EXISTS(SELECT 1 FROM provider_model LIMIT 1) \
           OR EXISTS(SELECT 1 FROM tenant_model LIMIT 1) \
           OR EXISTS(SELECT 1 FROM tenant_provider LIMIT 1) \
           OR EXISTS(SELECT 1 FROM provider_key LIMIT 1) \
           OR EXISTS(SELECT 1 FROM limit_role LIMIT 1) \
           OR EXISTS(SELECT 1 FROM provider_key_binding LIMIT 1)",
    )
    .fetch_one(pool)
    .await?;
    Ok(row.0 != 0)
}

/// What a re-seal pass did (see [`reseal_secrets`]).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ResealReport {
    /// Provider api-keys rewritten under the current key version.
    pub provider_keys_resealed: usize,
    /// Tenant certificate private keys rewritten under the current key version.
    pub tenant_certs_resealed: usize,
    /// `limit_role.matching_key` values rewritten under the current key version (decision D-16;
    /// includes pre-D-16 PLAINTEXT rows, which this pass seals for the first time).
    pub limit_keys_resealed: usize,
    /// Rows already at the current version (nothing to do).
    pub already_current: usize,
    /// Rows that could NOT be opened (unknown version / wrong key), left
    /// untouched. Non-empty means the rotation is INCOMPLETE.
    pub failed: Vec<String>,
}

impl ResealReport {
    /// True when every stored secret now opens under the current key version.
    #[must_use]
    pub fn is_complete(&self) -> bool {
        self.failed.is_empty()
    }
}

/// Re-encrypt every stored secret under the provider's CURRENT key version.
///
/// This is the missing half of master-key rotation. Before it existed, changing
/// `HYDRA_ENCRYPTION_KEY` made every ciphertext unopenable, so
/// `ConfigStore::load` failed and the process refused to start — and the admin
/// API that could have re-entered the keys needs that same process, so there was
/// no way back in short of editing the database by hand.
///
/// The procedure is: start once with the new key as
/// `HYDRA_ENCRYPTION_KEY` (+ `HYDRA_ENCRYPTION_KEY_VERSION`), the old key as
/// `HYDRA_ENCRYPTION_KEY_PREVIOUS` (+ `..._PREVIOUS_VERSION`) and
/// `HYDRA_RESEAL_SECRETS=1`. Every row is read AND rewritten inside ONE write
/// transaction, then the previous key can be dropped. Rows that cannot be opened
/// are REPORTED and left alone (never silently rewritten with garbage), and the
/// caller must exit non-zero so nobody believes an incomplete rotation succeeded.
///
/// Reads happen through the transaction on purpose: reading them from the pool
/// first would (a) read a different snapshot than the one being written and
/// (b) deadlock on a single-connection pool (`:memory:` in tests), which is how
/// this was caught.
pub async fn reseal_secrets(
    pool: &SqlitePool,
    kp: &dyn KeyProvider,
) -> Result<ResealReport, sqlx::Error> {
    let mut report = ResealReport::default();
    let current = kp.version();

    let mut tx = begin_write(pool).await?;

    // ---- provider api-keys -------------------------------------------------
    let rows: Vec<(String, Vec<u8>, Vec<u8>, i64)> = sqlx::query_as(
        "SELECT id, api_key_ciphertext, api_key_nonce, key_version FROM provider_key ORDER BY id",
    )
    .fetch_all(&mut *tx)
    .await?;
    for (id, ct, nonce, version) in rows {
        // A row whose version already equals the current one is NOT automatically
        // "already current". The version is an INDEPENDENT knob from the key
        // MATERIAL: rotate the key and forget to bump
        // `HYDRA_ENCRYPTION_KEY_VERSION` and every row still carries the old
        // number while the ring's slot for that number now holds different bytes.
        // Counting such a row as fine (and exiting 0) is the worst outcome in this
        // file, because the operator's next step is to delete the only key that can
        // open it — after which the process refuses to start with no way back. So
        // the claim is VERIFIED: the row must actually open under the current key,
        // which is what "already current" is supposed to mean.
        let version = version as u32;
        if version == current {
            match <[u8; crypto::NONCE_LEN]>::try_from(nonce.as_slice()) {
                Ok(nonce) => {
                    let sealed = Sealed {
                        ciphertext: ct,
                        nonce,
                        key_version: version,
                    };
                    if kp.open(&sealed).is_ok() {
                        report.already_current += 1;
                        continue;
                    }
                    report.failed.push(format!(
                        "provider_key {id}: labelled key_version {version} (the CURRENT \
                         version) but it does NOT open under the current key — the key was \
                         most likely rotated without bumping HYDRA_ENCRYPTION_KEY_VERSION. \
                         Do NOT delete the previous key until this is resolved"
                    ));
                }
                Err(_) => report
                    .failed
                    .push(format!("provider_key {id}: nonce has the wrong length")),
            }
            continue;
        }
        let Ok(nonce) = <[u8; crypto::NONCE_LEN]>::try_from(nonce.as_slice()) else {
            report
                .failed
                .push(format!("provider_key {id}: nonce has the wrong length"));
            continue;
        };
        let sealed = Sealed {
            ciphertext: ct,
            nonce,
            key_version: version,
        };
        match kp.open(&sealed) {
            Ok(plaintext) => match kp.seal(&plaintext) {
                Ok(fresh) => {
                    sqlx::query(
                        "UPDATE provider_key SET api_key_ciphertext = ?, api_key_nonce = ?, \
                         key_version = ? WHERE id = ?",
                    )
                    .bind(&fresh.ciphertext)
                    .bind(fresh.nonce.to_vec())
                    .bind(i64::from(fresh.key_version))
                    .bind(&id)
                    .execute(&mut *tx)
                    .await?;
                    report.provider_keys_resealed += 1;
                }
                Err(e) => report
                    .failed
                    .push(format!("provider_key {id}: seal failed: {e}")),
            },
            Err(e) => report.failed.push(format!(
                "provider_key {id}: cannot open key_version {version}: {e}"
            )),
        }
    }

    // ---- tenant certificate private keys ----------------------------------
    let cert_rows: Vec<(String, Vec<u8>, Vec<u8>, i64)> = sqlx::query_as(
        "SELECT id, cert_key_ciphertext, cert_key_nonce, cert_key_version FROM tenant \
         WHERE cert_key_ciphertext IS NOT NULL AND cert_key_nonce IS NOT NULL \
           AND cert_key_version IS NOT NULL ORDER BY id",
    )
    .fetch_all(&mut *tx)
    .await?;
    for (id, ct, nonce, version) in cert_rows {
        // A row whose version already equals the current one is NOT automatically
        // "already current". The version is an INDEPENDENT knob from the key
        // MATERIAL: rotate the key and forget to bump
        // `HYDRA_ENCRYPTION_KEY_VERSION` and every row still carries the old
        // number while the ring's slot for that number now holds different bytes.
        // Counting such a row as fine (and exiting 0) is the worst outcome in this
        // file, because the operator's next step is to delete the only key that can
        // open it — after which the process refuses to start with no way back. So
        // the claim is VERIFIED: the row must actually open under the current key,
        // which is what "already current" is supposed to mean.
        let version = version as u32;
        if version == current {
            match <[u8; crypto::NONCE_LEN]>::try_from(nonce.as_slice()) {
                Ok(nonce) => {
                    let sealed = Sealed {
                        ciphertext: ct,
                        nonce,
                        key_version: version,
                    };
                    if kp.open(&sealed).is_ok() {
                        report.already_current += 1;
                        continue;
                    }
                    report.failed.push(format!(
                        "tenant {id} cert: labelled key_version {version} (the CURRENT \
                         version) but it does NOT open under the current key — the key was \
                         most likely rotated without bumping HYDRA_ENCRYPTION_KEY_VERSION. \
                         Do NOT delete the previous key until this is resolved"
                    ));
                }
                Err(_) => report
                    .failed
                    .push(format!("tenant {id} cert: nonce has the wrong length")),
            }
            continue;
        }
        let Ok(nonce) = <[u8; crypto::NONCE_LEN]>::try_from(nonce.as_slice()) else {
            report
                .failed
                .push(format!("tenant {id} cert: nonce has the wrong length"));
            continue;
        };
        let sealed = Sealed {
            ciphertext: ct,
            nonce,
            key_version: version,
        };
        match kp.open(&sealed) {
            Ok(plaintext) => match kp.seal(&plaintext) {
                Ok(fresh) => {
                    sqlx::query(
                        "UPDATE tenant SET cert_key_ciphertext = ?, cert_key_nonce = ?, \
                         cert_key_version = ? WHERE id = ?",
                    )
                    .bind(&fresh.ciphertext)
                    .bind(fresh.nonce.to_vec())
                    .bind(i64::from(fresh.key_version))
                    .bind(&id)
                    .execute(&mut *tx)
                    .await?;
                    report.tenant_certs_resealed += 1;
                }
                Err(e) => report
                    .failed
                    .push(format!("tenant {id} cert: seal failed: {e}")),
            },
            Err(e) => report.failed.push(format!(
                "tenant {id} cert: cannot open key_version {version}: {e}"
            )),
        }
    }

    // ---- limit_role.matching_key (decision D-16) --------------------------
    //
    // A third sealed column, added 2026-10-08. It has no `key_version` column of its own — the
    // version lives inside the envelope — so the "already current" test below reads it from there.
    // Two cases are handled, and they are different pieces of work:
    //   * a pre-D-16 PLAINTEXT value: sealing it is a MIGRATION, not a rotation, and this pass is
    //     the second of the two places that do it (the loader is the first, and the usual one);
    //   * a sealed value with an older version: the rotation this command exists for.
    let key_rows: Vec<(String, String)> = sqlx::query_as(
        "SELECT id, matching_key FROM limit_role WHERE matching_key IS NOT NULL ORDER BY id",
    )
    .fetch_all(&mut *tx)
    .await?;
    for (id, value) in key_rows {
        let Some(sealed) = Sealed::from_text(&value) else {
            match kp.seal(value.as_bytes()) {
                Ok(fresh) => {
                    sqlx::query("UPDATE limit_role SET matching_key = ? WHERE id = ?")
                        .bind(fresh.to_text())
                        .bind(&id)
                        .execute(&mut *tx)
                        .await?;
                    report.limit_keys_resealed += 1;
                }
                Err(e) => report
                    .failed
                    .push(format!("limit_role {id} matching_key: seal failed: {e}")),
            }
            continue;
        };
        if sealed.key_version == current {
            // Same rule as the two blocks above: the version tag is an independent knob from the key
            // material, so "already current" is VERIFIED by opening the value, not assumed from the
            // number. Counting an unopenable row as fine is how the operator ends up deleting the
            // only key that can read it.
            match kp.open(&sealed) {
                Ok(_) => report.already_current += 1,
                Err(e) => report.failed.push(format!(
                    "limit_role {id} matching_key: labelled key_version {current} (the CURRENT \
                     version) but it does NOT open under the current key — the key was most likely \
                     rotated without bumping HYDRA_ENCRYPTION_KEY_VERSION. Do NOT delete the \
                     previous key until this is resolved: {e}"
                )),
            }
            continue;
        }
        match kp.open(&sealed) {
            Ok(plaintext) => match kp.seal(&plaintext) {
                Ok(fresh) => {
                    sqlx::query("UPDATE limit_role SET matching_key = ? WHERE id = ?")
                        .bind(fresh.to_text())
                        .bind(&id)
                        .execute(&mut *tx)
                        .await?;
                    report.limit_keys_resealed += 1;
                }
                Err(e) => report
                    .failed
                    .push(format!("limit_role {id} matching_key: seal failed: {e}")),
            },
            Err(e) => report.failed.push(format!(
                "limit_role {id} matching_key: cannot open key_version {}: {e}",
                sealed.key_version
            )),
        }
    }

    // One commit for both tables: a re-seal that failed halfway would leave the
    // rotation in a state where neither "before" nor "after" is true of the whole
    // DB, which is exactly what an operator cannot reason about.
    tx.commit().await?;
    Ok(report)
}

/// Persist the last-applied config version (upsert).
pub async fn set_config_version(pool: &SqlitePool, version: u64) -> Result<(), sqlx::Error> {
    sqlx::query(
        "INSERT INTO config_meta (key, value) VALUES ('config_version', ?) \
         ON CONFLICT(key) DO UPDATE SET value = excluded.value",
    )
    .bind(version.to_string())
    .execute(pool)
    .await?;
    Ok(())
}

mod restore;

pub use restore::restore_config;

/// A migrated in-memory SQLite pool, for unit tests inside this crate.
///
/// The same recipe as `tests/common/mod.rs::setup_pool` — which the integration tests use and the
/// crate's own `#[cfg(test)]` modules cannot reach — and it lives here so the recipe has ONE owner:
/// `init_pool` pins a `:memory:` pool to a single connection, which is what makes the migrations
/// visible to every later query in the test.
#[cfg(test)]
pub(crate) async fn test_pool() -> SqlitePool {
    let pool = init_pool("sqlite::memory:")
        .await
        .expect("init_pool should connect to :memory:");
    run_migrate(&pool)
        .await
        .expect("run_migrate should create the schema");
    pool
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crypto::{StaticKeyProvider, KEY_LEN};

    const LEGACY: &str = "sk-legacy-plaintext-key";

    /// Write a row the way the code did BEFORE decision D-16: plaintext, straight into the column.
    /// (`insert_limit_role` seals, so the legacy state cannot be produced through it any more.)
    async fn insert_plaintext_role(pool: &SqlitePool, id: &str, key: &str) {
        sqlx::query(
            "INSERT INTO limit_role (id, name, matching_key, limit_count, window, enabled, \
             created_at) VALUES (?, ?, ?, 600, 'm', 1, '')",
        )
        .bind(id)
        .bind(id)
        .bind(key)
        .execute(pool)
        .await
        .expect("insert a pre-D-16 plaintext row");
    }

    async fn stored(pool: &SqlitePool, id: &str) -> Option<String> {
        let row: Option<(Option<String>,)> =
            sqlx::query_as("SELECT matching_key FROM limit_role WHERE id = ?")
                .bind(id)
                .fetch_optional(pool)
                .await
                .expect("select");
        row.and_then(|r| r.0)
    }

    /// The legacy re-seal is a COMPARE-AND-SWAP, driven here through BOTH production halves in the
    /// order the race happens: read the pending row, let the row change, then write the stale
    /// envelope.
    ///
    /// Why a unit test and not an integration one: this is the ONLY way to hold the two halves apart,
    /// and the first version of this test wrote the CAS statement out by hand — it stayed GREEN when
    /// the production clause was deleted, i.e. it was asserting a copy of the code. The helper split
    /// exists for this test (`legacy_limit_key_rows` + `reseal_limit_key_row`).
    ///
    /// Falsification: drop `AND matching_key = ?` from `reseal_limit_key_row` and the first two
    /// assertions fail — the stale envelope wins and the newer key is silently destroyed.
    #[tokio::test]
    async fn the_legacy_reseal_refuses_a_row_that_changed_after_the_read() {
        let pool = test_pool().await;
        let kp = StaticKeyProvider::new([3u8; KEY_LEN], 1);
        insert_plaintext_role(&pool, "r-cas", LEGACY).await;

        // 1) the migration's READ.
        let pending = legacy_limit_key_rows(&pool)
            .await
            .expect("read the pending rows");
        assert_eq!(
            pending,
            vec![("r-cas".to_string(), LEGACY.to_string())],
            "fixture: the row must be pending"
        );

        // 2) the row changes underneath it — an admin write, or another node sealing it first.
        let newer = kp.seal(b"sk-written-in-between").expect("seal").to_text();
        sqlx::query("UPDATE limit_role SET matching_key = ? WHERE id = ?")
            .bind(&newer)
            .bind("r-cas")
            .execute(&pool)
            .await
            .expect("the concurrent write");

        // 3) the migration's WRITE, carrying the value it read.
        let stale = kp.seal(LEGACY.as_bytes()).expect("seal").to_text();
        let mut tx = begin_write(&pool).await.expect("tx");
        let rewritten = reseal_limit_key_row(&mut *tx, "r-cas", LEGACY, &stale)
            .await
            .expect("compare-and-swap");
        tx.commit().await.expect("commit");

        assert_eq!(
            rewritten, 0,
            "a row whose value changed after the read must NOT be rewritten (the CAS is what \
             makes the migration safe to run on a live node)"
        );
        assert_eq!(
            stored(&pool, "r-cas").await.as_deref(),
            Some(newer.as_str()),
            "the newer key must survive the migration's stale read"
        );
    }

    /// ...and the same CAS still rewrites a row that did NOT change, so "refuse everything" would not
    /// pass the test above. This one goes through the full production entry point.
    ///
    /// Falsification: return 0 from `reseal_limit_key_row` unconditionally (the lazy way to pass the
    /// test above) and this fails.
    #[tokio::test]
    async fn the_legacy_reseal_rewrites_a_row_that_did_not_change() {
        let pool = test_pool().await;
        let kp = StaticKeyProvider::new([3u8; KEY_LEN], 1);
        insert_plaintext_role(&pool, "r-still", LEGACY).await;

        assert_eq!(
            seal_legacy_limit_keys(&pool, &kp).await.expect("migrate"),
            1,
            "the one plaintext row must be rewritten"
        );
        let after = stored(&pool, "r-still").await.expect("still has a key");
        assert!(
            after.starts_with(crate::crypto::SEALED_TEXT_PREFIX) && !after.contains(LEGACY),
            "the column must hold an envelope afterwards: {after}"
        );
        assert_eq!(
            open_limit_key(&kp, Some(after)).expect("open").as_deref(),
            Some(LEGACY),
            "…and the key itself must come back"
        );
        assert_eq!(
            seal_legacy_limit_keys(&pool, &kp)
                .await
                .expect("second pass"),
            0,
            "a sealed database needs no write at all"
        );
    }
}
