#!/usr/bin/env python3
"""The tenant TypeScript SDK (`tools/hydra-ts`) against a LIVE node.

`tools/hydra-ts` documents exactly the same tenant contract as `tools/hydra-py`
(`README.md`: `200 applied` / `200 single_node` = done, `202 pending` is NOT done,
`503 unavailable` = the fleet was never told, `X-Hydra-Trace-Id` survives to the
caller, the endpoint is on the DATA plane and NOT the admin port). Round 80 pointed the
Python SDK at a real gateway; the TypeScript one had never left its mocked suite — and
two implementations of one documented contract can drift. This drill runs the TS SDK
against a real node (single-node legs), against a real bus (cluster legs), and finally
compares what the two SDKs report about the SAME node.

The TS SDK is exercised through a small generated Node driver (`DRIVER`), which imports
the built `dist/client.js` and prints one JSON object per leg on stdout.

Legs (server feature set, no Redis needed):
  T1 the documented usage        -> 200 single_node, isDoneState, trace id, node counts
  T2 the call really CLEARS      -> allow, flip to deny (still served = cached), TS SDK
                                    invalidate -> 401
  T3 another tenant's token      -> HTTPError, not a "done" state
  T4 the management path is gone -> 404 on the admin port
The `--cluster` legs (C1-C3 plus the TS/Python parity leg: `applied` + an `event_id`,
`202 pending` -> InvalidatePendingError, `503 unavailable` -> InvalidateUnavailableError on a node
whose bus is cut) were RETIRED on 2026-10-07 with the topology they measured: they started two
PLAIN single-node instances (`HYDRA_REDIS_MODE=single`, no `HYDRA_CLUSTER_PEERS`), which correctly
answer `state: "single_node"`, so every C1-C3 assertion had been false since ADR-0001 replaced the
Redis leader lease with raft. The retired CI steps in `.github/workflows/ci.yml` record where each
half of that coverage lives now.

Run: python3 integration/test_sdk_ts_live.py
Exit 0 pass · 1 an assertion failed · 2 could not verify.
"""
import json
import os
import shutil
import signal
import socket
import socketserver
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from _usage_env import usage_env

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIR = os.path.join(ROOT, ".acceptance", "sdk-ts-live")
BIN = os.environ.get("HYDRA_BIN", os.path.join(ROOT, "target", "debug", "hydra"))
SDK = os.path.join(ROOT, "tools", "hydra-ts")
CLIENT = os.path.join(SDK, "dist", "client.js")
DRIVER = os.path.join(DIR, "driver.mjs")

ADMIN, DATA = 18760, 18761
UPSTREAM = 18769
TOKEN = "hydra-sdk-ts-admin-2026"
TENANT_TOKEN = "tenant-ts-self-service-2026"
OTHER_TOKEN = "another-tenants-token-20260930"
REDIS = os.environ.get("HYDRA_TEST_REDIS_URL", "redis://127.0.0.1:6380")

failures = []


def check(label, ok, detail=""):
    print(f"   {'PASS' if ok else 'FAIL'}  {label}{'  — ' + detail if detail else ''}")
    if not ok:
        failures.append(label)


def announce(label, detail):
    print(f"   ....  {label}{'  — ' + detail if detail else ''}")


def call(method, url, token=None, body=None, timeout=30):
    data = None if body is None else json.dumps(body).encode()
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    req = urllib.request.Request(url, data=data, method=method, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.status, r.read().decode(errors="replace")
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode(errors="replace")
    except Exception as e:
        return 0, str(e)


class AuthUpstream(BaseHTTPRequestHandler):
    allowed = True

    def do_POST(self):
        length = int(self.headers.get("Content-Length", 0))
        if length:
            self.rfile.read(length)
        body = json.dumps({"allowed": AuthUpstream.allowed, "reason": "sdk-ts",
                           "expires_in": 300}).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *a):
        pass










DRIVER_SOURCE = """\
// Generated by integration/test_sdk_ts_live.py — drives the BUILT TS SDK.
import { HydraClient, isDoneState } from %(client)s;

const [mode, base, token, tenant, ...rest] = process.argv.slice(2);
const out = (o) => process.stdout.write(JSON.stringify(o));

function describe(res) {
  return {
    httpStatus: res.httpStatus, state: res.state, done: isDoneState(res.state),
    nodesApplied: res.nodesApplied, nodesTotal: res.nodesTotal, lagging: res.lagging,
    eventId: res.eventId ?? null, waitedMs: res.waitedMs ?? null,
    traceId: res.traceId ?? null, node: res.node, checked: res.checked,
  };
}

const waitMode = mode.startsWith('none') ? 'none' : undefined;
const client = new HydraClient({ token, nodes: [base], waitMode, disableBackgroundRecheck: true });
try {
  if (mode === 'result' || mode === 'none-result') {
    const res = await client.invalidateWithResult(tenant);
    out({ ok: true, result: describe(res) });
  } else if (mode === 'raise' || mode === 'none-raise') {
    try {
      await client.invalidateTenantAuthCache(tenant);
      out({ ok: true, raised: null });
    } catch (e) {
      out({
        ok: true, raised: e?.constructor?.name ?? 'Error', message: String(e?.message ?? '').slice(0, 120),
        result: e?.result ? describe(e.result) : null,
      });
    }
  } else {
    out({ ok: false, error: 'unknown mode ' + mode });
  }
} catch (e) {
  out({ ok: false, error: e?.constructor?.name + ': ' + String(e?.message ?? '').slice(0, 160) });
} finally {
  client.close();
}
"""


def write_driver():
    # The SDK is ESM; the driver is a module in the sidecar dir importing the built file
    # by absolute path (file:// URL) so node resolves it regardless of cwd.
    src = DRIVER_SOURCE % {"client": json.dumps("file://" + CLIENT)}
    with open(DRIVER, "w", encoding="utf-8") as f:
        f.write(src)


def ts(mode, base, token, tenant="t1", timeout=60):
    p = subprocess.run(["node", DRIVER, mode, base, token, tenant],
                       capture_output=True, text=True, timeout=timeout)
    try:
        return json.loads(p.stdout), p.returncode, p.stderr
    except Exception:
        return None, p.returncode, (p.stdout + p.stderr)[:300]


def node_env(admin, data, label, extra=None):
    env = dict(os.environ)
    env.update(usage_env())
    env.update({
        "HYDRA_ADMIN_TOKEN": TOKEN, "HYDRA_ADMIN_ADDR": f"127.0.0.1:{admin}",
        "HYDRA_LISTEN": f"127.0.0.1:{data}",
        "HYDRA_DB_URL": f"sqlite://{os.path.join(DIR, label)}.db?mode=rwc",
        "HYDRA_ENCRYPTION_KEY": "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=",
        "RUST_LOG": "warn",
    })
    if extra:
        env.update(extra)
    return env


def start(admin, data, label, extra=None):
    log = open(os.path.join(DIR, f"{label}.log"), "w")
    return subprocess.Popen([BIN], env=node_env(admin, data, label, extra),
                            stdout=log, stderr=subprocess.STDOUT)


def wait_healthy(admin, token=TOKEN, budget=25.0):
    deadline = time.time() + budget
    while time.time() < deadline:
        if call("GET", f"http://127.0.0.1:{admin}/api/v1/health", token=token)[0] == 200:
            return True
        time.sleep(0.25)
    return False






def stop(proc):
    if proc is None:
        return
    if proc.poll() is None:
        proc.send_signal(signal.SIGKILL)
        proc.wait(timeout=10)


def seed_core(admin):
    for path, payload in [
        ("providers", {"id": "p1", "key": "p1", "name": "P", "endpoint": f"http://127.0.0.1:{UPSTREAM}",
                       "weight": 1, "created_at": "", "updated_at": ""}),
        ("provider-models", {"id": "pm1", "key": "echo", "name": "E", "provider_id": "p1",
                             "status": 1, "created_at": "", "updated_at": ""}),
        ("provider-keys", {"id": "pk1", "provider_id": "p1", "api_key": "sk-up", "created_at": ""}),
    ]:
        st, out = call("POST", f"http://127.0.0.1:{admin}/api/v1/{path}", token=TOKEN, body=payload)
        if st not in (200, 201):
            raise SystemExit(f"[sdk-ts] CANNOT VERIFY: seeding {path} -> {st} {out[:160]}")


def seed_tenant(admin, tenant_id, tenant_token, domain):
    for path, payload in [
        ("tenants", {"id": tenant_id, "name": "T", "domain": domain,
                     "auth_url": f"http://127.0.0.1:{UPSTREAM}/auth", "enabled": True,
                     "access_token": tenant_token,
                     "cert_key": None, "cert_file": None, "created_at": "", "updated_at": ""}),
        ("tenant-providers", {"id": f"tp-{tenant_id}", "tenant_id": tenant_id, "provider_id": "p1",
                              "created_at": "", "updated_at": ""}),
        ("tenant-models", {"id": f"tm-{tenant_id}", "tenant_id": tenant_id, "model_key": "echo",
                           "created_at": "", "updated_at": ""}),
    ]:
        st, out = call("POST", f"http://127.0.0.1:{admin}/api/v1/{path}", token=TOKEN, body=payload)
        if st not in (200, 201):
            raise SystemExit(f"[sdk-ts] CANNOT VERIFY: seeding {path} -> {st} {out[:160]}")
    call("POST", f"http://127.0.0.1:{admin}/api/v1/reload", token=TOKEN, body={})
    time.sleep(0.3)


def proxied(data_port, api_key="sk-tenant-1"):
    body = {"model": "echo", "messages": [{"role": "user", "content": "hi"}]}
    req = urllib.request.Request(
        f"http://127.0.0.1:{data_port}/v1/chat/completions",
        data=json.dumps(body).encode(), method="POST",
        headers={"Content-Type": "application/json", "Host": "load.local",
                 "Authorization": f"Bearer {api_key}"})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return r.status, r.read().decode(errors="replace")
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode(errors="replace")
    except Exception as e:
        return 0, str(e)


def python_sdk_result(base, token, tenant):
    """The OTHER implementation of the same contract (tools/hydra-py), for the parity leg."""
    sys.path.insert(0, os.path.join(ROOT, "tools", "hydra-py"))
    from hydra_sdk import HydraClient  # noqa: E402
    client = HydraClient(token=token, nodes=[base], disable_background_recheck=True)
    try:
        res = client.invalidate_with_result(tenant)
        return res
    finally:
        client.close()


def leg_single_node():
    node = start(ADMIN, DATA, "single")
    try:
        if not wait_healthy(ADMIN):
            print("[sdk-ts] CANNOT VERIFY: the node never became healthy", file=sys.stderr)
            print(open(os.path.join(DIR, "single.log")).read()[-600:], file=sys.stderr)
            return 2
        seed_core(ADMIN)
        seed_tenant(ADMIN, "t1", TENANT_TOKEN, "load.local")
        seed_tenant(ADMIN, "t2", OTHER_TOKEN, "other.local")
        base = f"http://127.0.0.1:{DATA}"

        # ---- T1: the documented usage -----------------------------------------
        got, rc, err = ts("result", base, TENANT_TOKEN)
        check("T1: the TS SDK's documented call returns a result", bool(got and got.get("ok")),
              f"rc={rc} out={got} err={err[:120]}")
        if got and got.get("ok"):
            res = got["result"]
            announce("T1 the TS SDK's documented call", f"{res}")
            check("T1: a single data-plane node answers 200 single_node",
                  res["httpStatus"] == 200 and res["state"] == "single_node", f"{res['httpStatus']}")
            check("T1: ...which the SDK reports as done (`isDoneState`)", res["done"] is True)
            check("T1: the X-Hydra-Trace-Id survives to the caller", bool(res["traceId"]),
                  f"traceId={res['traceId']!r}")
            check("T1: node counts are filled in (not invented)",
                  isinstance(res["nodesTotal"], int) and res["nodesTotal"] >= 1, f"{res['nodesTotal']}")

        # ---- T2: does it really clear the cache? ------------------------------
        AuthUpstream.allowed = True
        st_allow, _ = proxied(DATA)
        AuthUpstream.allowed = False
        st_cached, _ = proxied(DATA)
        got, rc, err = ts("raise", base, TENANT_TOKEN)
        st_after, body_after = proxied(DATA)
        announce("T2 requests", f"allow={st_allow} after-flip={st_cached} after-invalidate={st_after}")
        check("T2: the verdict is cached (the flip alone does not change the answer)",
              st_allow == 200 and st_cached == 200, f"{st_allow}/{st_cached}")
        check("T2: after the TS SDK's invalidate the cached allow is GONE",
              st_after == 401, f"HTTP {st_after} {body_after[:60]}")
        AuthUpstream.allowed = True

        # ---- T3: another tenant's token ---------------------------------------
        got, rc, err = ts("raise", base, OTHER_TOKEN)
        raised = (got or {}).get("raised")
        check("T3: another tenant's token is refused (HTTPError, not a 'done' state)",
              raised == "HTTPError", f"raised={raised} out={got}")

        # ---- T4: the management path is gone ----------------------------------
        for path in ("/api/v1/tenants/t1/auth/cache/invalidate",
                     "/api/v1/tenant/t1/api/v1/auth/cache/invalidate"):
            st, body = call("POST", f"http://127.0.0.1:{ADMIN}{path}", token=TOKEN, body={})
            check(f"T4: the old management path {path} does not exist", st == 404,
                  f"HTTP {st} {body[:60]}")
    finally:
        stop(node)
    return 0


def main():
    if not os.path.exists(BIN):
        print(f"[sdk-ts] CANNOT VERIFY: {BIN} is not built", file=sys.stderr)
        return 2
    if not os.path.exists(CLIENT):
        print(f"[sdk-ts] CANNOT VERIFY: {CLIENT} is not built "
              f"(cd tools/hydra-ts && npm install && npm run build)", file=sys.stderr)
        return 2
    shutil.rmtree(DIR, ignore_errors=True)
    os.makedirs(DIR, exist_ok=True)
    write_driver()

    upstream = ThreadingHTTPServer(("127.0.0.1", UPSTREAM), AuthUpstream)
    threading.Thread(target=upstream.serve_forever, daemon=True).start()
    try:
        rc = leg_single_node()
        if rc:
            return rc
    finally:
        upstream.shutdown()

    print()
    if failures:
        print(f"SDK-TS LIVE: FAILED ({len(failures)}): " + "; ".join(failures))
        return 1
        print("SDK-TS LIVE: PASSED (documented usage, single_node, cache really cleared, other "
              "tenant refused, management-API path gone)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
